import assert from 'node:assert/strict';
import fs from 'node:fs';
import {hasUsableTwseQuote,pickBetterTwseRow,resolveTwseCurrentPrice,resolveTwsePreviousClose} from '../src/market/twseQuoteParser';

assert.equal(resolveTwseCurrentPrice({z:'110.65',y:'109.85'}),110.65);
assert.equal(resolveTwseCurrentPrice({z:'-',pz:'999.00',b:'110.55_110.50_',a:'110.65_',y:'109.85'}),110.55);
assert.equal(resolveTwseCurrentPrice({z:'-',b:'56.70_56.65_',a:'56.75_',y:'56.85'}),56.70);
assert.equal(resolveTwseCurrentPrice({z:'-',b:'',a:'63.45_63.50_',y:'63.85'}),63.45);
assert.equal(resolveTwseCurrentPrice({z:'-',pz:'88.88',b:'',a:'',y:'34.83'}),0);
assert.equal(resolveTwsePreviousClose({y:'109.85'}),109.85);
assert.equal(hasUsableTwseQuote({z:'-',b:'',a:'',y:'34.83'}),false);
assert.equal(pickBetterTwseRow({z:'-',y:'100'},{z:'101',y:'100'}).z,'101');

const market=fs.readFileSync('src/market/MarketRuntime.tsx','utf8');
const finance=fs.readFileSync('src/finance/FinanceRuntime.tsx','utf8');
const app=fs.readFileSync('App.tsx','utf8');
const home=fs.readFileSync('src/screens/HomeScreen.tsx','utf8');
const portfolio=fs.readFileSync('src/screens/PortfolioScreen.tsx','utf8');
const detail=fs.readFileSync('src/screens/HoldingDetailScreen.tsx','utf8');
assert.match(market,/MarketDataCenter/);
assert.match(market,/TwseMisQuoteProvider/);
assert.match(market,/YahooQuoteProvider/);
assert.match(market,/FugleWebSocketProvider/);
assert.match(market,/unresolvedSymbols/);
assert.match(market,/未解析行情/);
assert.match(market,/refreshPromiseRef/);
assert.match(market,/force:true/);
assert.match(market,/\[hydrated,trackedSymbols,refresh\]/);
assert.match(finance,/\[entries,market\.setTrackedSymbols\]/);
assert.match(finance,/\[initialCash,entries,canonicalQuotes\]/);
assert.match(finance,/buildSharedSnapshot/);
assert.match(app,/syncNativeWidget\(widgetSettings\.config,finance\.sharedSnapshot\)/);
assert.match(app,/syncNativeMonitor\(monitorSettings\.config,finance\.sharedSnapshot\)/);
assert.match(home,/finance\.holdings/);
assert.match(portfolio,/finance\.holdings/);
assert.match(detail,/useFinance\(\)/);
console.log('V1.0.10 REALTIME MARKET LINKAGE: PASS');
