const fs=require('fs');const assert=require('assert');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const app=JSON.parse(fs.readFileSync('app.json','utf8'));
const settings=fs.readFileSync('src/screens/SettingsScreen.tsx','utf8');
const ci=fs.readFileSync('.github/workflows/ci.yml','utf8');
const workflow=fs.readFileSync('.github/workflows/release-v1.yml','utf8');
assert.equal(pkg.version,'1.0.18');
assert.equal(app.expo.version,'1.0.18');
assert.equal(app.expo.android.versionCode,10018);
assert.equal(app.expo.android.package,'com.tfasset.app');
assert.match(settings,/const VERSION='1\.0\.18';/);
assert.match(settings,/const BUILD='10018';/);
assert.match(ci,/V1\.0\.18 Hard Gates/);
assert.match(ci,/npm run test:v118/);
assert.match(workflow,/TF Asset V1\.0\.18 GitHub APK/);
assert.match(workflow,/versionCode 10018/);
assert.match(workflow,/versionName "1\.0\.18"/);
assert.match(workflow,/TF-Asset-V1\.0\.18-github\.apk/);
assert.ok(!/eas\s+build/i.test(workflow));
console.log('V1.0.18 RELEASE IDENTITY: PASS');
