const fs=require('fs');const assert=require('assert');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const app=JSON.parse(fs.readFileSync('app.json','utf8'));
const settings=fs.readFileSync('src/screens/SettingsScreen.tsx','utf8');
const ci=fs.readFileSync('.github/workflows/ci.yml','utf8');
const release=fs.readFileSync('.github/workflows/release-v1.yml','utf8');
assert.equal(pkg.version,'1.0.16');assert.equal(app.expo.version,'1.0.16');assert.equal(app.expo.android.versionCode,10016);assert.equal(app.expo.android.package,'com.tfasset.app');
assert.match(settings,/const VERSION='1\.0\.16';/);assert.match(settings,/const BUILD='10016';/);
assert.match(ci,/V1\.0\.16 Hard Gates/);assert.match(ci,/npm run test:v116/);
assert.match(release,/TF Asset V1\.0\.16 GitHub APK/);assert.match(release,/versionCode 10016/);assert.match(release,/versionName "1\.0\.16"/);assert.match(release,/TF-Asset-V1\.0\.16-github\.apk/);
assert.ok(!/eas\s+build/i.test(release));console.log('V1.0.16 RELEASE IDENTITY: PASS');
