const fs=require('fs');const assert=require('assert');
const home=fs.readFileSync('src/screens/HomeScreen.tsx','utf8');
const overlay=fs.readFileSync('native/android/TfAssetOverlayService.kt','utf8');
const native=fs.readFileSync('native/android/TfAssetNativeModule.kt','utf8');
const bridge=fs.readFileSync('src/native/TfAssetNativeBridge.ts','utf8');
const app=fs.readFileSync('App.tsx','utf8');
const ai=fs.readFileSync('src/ai/AiNewsRuntime.tsx','utf8');
const aiScreen=fs.readFileSync('src/screens/AiScreen.tsx','utf8');
const modal=fs.readFileSync('src/components/PageFrameSettingsModal.tsx','utf8');
assert.match(home,/更新行情/);
assert.match(home,/總資產（持股市值）/);
assert.match(home,/portfolio\.totalMarketValue/);
assert.ok(!home.includes('DEMO_NEWS'),'home news must not use demo news');
assert.match(home,/aiNews\.items/);
assert.match(ai,/news\.google\.com\/rss\/search/);
for(const token of ['symbol','name','title','source','publishedAt','summary'])assert.ok(ai.includes(token),'AI news field missing '+token);
assert.match(aiScreen,/AI 持股新聞/);
assert.match(modal,/新聞顯示筆數/);
assert.match(modal,/僅顯示持股相關/);
assert.match(overlay,/applyConfiguredLayoutIfChanged\(cfg\);render\(\)/);
assert.ok(!/val cfg=readConfig\(\)\n\s*applyConfiguredLayoutIfChanged\(cfg\)\n\s*val snap/.test(overlay),'render must not force persisted mode after local double tap');
for(const label of ['更新行情','縮小','關閉'])assert.ok(overlay.includes(label),'overlay control missing '+label);
assert.match(overlay,/monitor_force_refresh_requested_at/);
assert.match(overlay,/monitor_user_closed/);
assert.match(native,/consumeMonitorForceRefreshRequest/);
assert.match(bridge,/consumeNativeMonitorForceRefreshRequest/);
assert.match(app,/consumeNativeMonitorForceRefreshRequest/);
assert.match(app,/case 'ai'/);
console.log('V1.0.16 AI/news/editor/monitor regression: PASS');
