const fs=require('fs');const assert=require('assert');
const home=fs.readFileSync('src/screens/HomeScreen.tsx','utf8');
const overlay=fs.readFileSync('native/android/TfAssetOverlayService.kt','utf8');
const native=fs.readFileSync('native/android/TfAssetNativeModule.kt','utf8');
const bridge=fs.readFileSync('src/native/TfAssetNativeBridge.ts','utf8');
const app=fs.readFileSync('App.tsx','utf8');
const ai=fs.readFileSync('src/ai/AiNewsRuntime.tsx','utf8');
const aiScreen=fs.readFileSync('src/screens/AiScreen.tsx','utf8');
const modal=fs.readFileSync('src/components/PageFrameSettingsModal.tsx','utf8');
assert.match(home,/更新行情/);
assert.match(home,/總資產（持股市值）/);
assert.match(home,/portfolio\.totalMarketValue/);
assert.ok(!home.includes('DEMO_NEWS'),'home news must not use demo news');
assert.match(home,/aiNews\.items/);
assert.match(ai,/news\.google\.com\/rss\/search/);
for(const token of ['symbol','name','title','source','publishedAt','summary'])assert.ok(ai.includes(token),'AI news field missing '+token);
assert.match(aiScreen,/AI 持股新聞/);
assert.match(modal,/新聞顯示筆數/);
assert.match(modal,/僅顯示持股相關/);
assert.match(overlay,/applyConfiguredLayoutIfChanged\(cfg\);render\(\)/);
assert.ok(!/val cfg=readConfig\(\)\n\s*applyConfiguredLayoutIfChanged\(cfg\)\n\s*val snap/.test(overlay),'render must not force persisted mode after local double tap');
for(const label of ['更新行情','縮小','關閉'])assert.ok(overlay.includes(label),'overlay control missing '+label);
assert.match(overlay,/monitor_force_refresh_requested_at/);
assert.match(overlay,/monitor_user_closed/);
assert.match(native,/consumeMonitorForceRefreshRequest/);
assert.match(bridge,/consumeNativeMonitorForceRefreshRequest/);
assert.match(app,/consumeNativeMonitorForceRefreshRequest/);
assert.match(app,/aiHoldingKey/,'holding identity changes must drive AI news refresh');
assert.ok(!app.includes('if(aiNews.lastUpdatedAt==null)'),'AI news refresh must not be initial-load only');
assert.ok(!app.includes('startNativeMonitor();'),'App sync must not auto-reopen a user-closed Monitor');
assert.match(native,/putBoolean\("monitor_user_closed",false\)/,'explicit Monitor start must clear user-closed latch');
assert.match(native,/monitor_last_config_mode/,'native sync must track configured mode changes');
assert.match(overlay,/monitor_runtime_mode_override/,'double tap/minimize mode must persist across refresh sync');
assert.match(overlay,/putString\("monitor_runtime_mode_override",mode\)/,'local mode toggle must save runtime override');
assert.match(aiScreen,/usePageEditor\('ai'\)/,'AI page must consume its editor config');
assert.match(aiScreen,/PageEditorStack/,'AI frame visibility/order settings must apply');
assert.match(aiScreen,/newsVisibleCount/,'AI page news count setting must apply');
assert.match(aiScreen,/newsHoldingsOnly/,'AI page holdings-only setting must apply');
assert.match(home,/newsHoldingsOnly/,'Home holdings-only news setting must apply');
assert.match(modal,/pageKey==='ai'&&frame\.key==='ai-news'/,'AI news frame must expose display editor');
assert.match(app,/case 'ai'/);
console.log('V1.0.16 AI/news/editor/monitor regression: PASS');
