const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=p=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const app=JSON.parse(read('app.json'));
const settings=read('src/screens/SettingsScreen.tsx');
const ledger=read('src/screens/LedgerScreen.tsx');
const calendar=read('src/dividend/dividendCalendar.ts');
const dividend=read('src/screens/DividendScreen.tsx');
const prefs=read('src/settings/SettingsRuntime.tsx');
const backup=read('src/settings/BackupService.ts');
const ci=read('.github/workflows/ci.yml');
// Supported QA identities must match all user-visible, backup and native build metadata.
const [major,minor,patch]=pkg.version.split('.').map(Number);
assert.ok(Number.isInteger(major)&&Number.isInteger(minor)&&Number.isInteger(patch)&&major>=3,'unsupported QA version');
const expectedCode=major*10000+minor*100+patch;
assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,expectedCode);
assert.equal(app.expo.android.package,'com.tfasset.app');
assert.ok(settings.includes("const VERSION='"+pkg.version+"'"),'visible app version mismatch');
assert.ok(settings.includes("const BUILD='"+expectedCode+"'"),'visible app build mismatch');
assert.ok(backup.includes("const APP_VERSION='"+pkg.version+"'"),'backup version mismatch');
assert.ok(ci.includes('TF-Asset-V'+pkg.version+'-QA.apk'),'APK artifact identity mismatch');
assert.match(ledger,/onPress=\{\(\)=>setSelectedEntry\(row\)\}/);
assert.match(ledger,/Alert\.alert\('刪除交易紀錄？'/);
assert.match(calendar,/lastBuyDate/);
assert.match(calendar,/dateFromNote\(entry\.note,'最後購買日'\)/);
assert.match(dividend,/最後購買日/);
assert.match(prefs,/showLastBuyDate/);
for(const core of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(fs.existsSync(core),core);
console.log('Current QA identity + ledger details + explicit dividend last-buy source smoke: PASS');
