import assert from 'node:assert/strict';
import fs from 'node:fs';
import {holdingPreviewLayout,previewLimit,clampPreviewPosition} from '../src/editor/holdingPreviewModel';

for(const mode of ['grid2','paged2'])assert.equal(holdingPreviewLayout(mode),'narrow',mode);
assert.equal(holdingPreviewLayout('grid3'),'micro','three columns use chart-free micro card');
for(const mode of ['list','horizontal',undefined])assert.equal(holdingPreviewLayout(mode),'full',String(mode));
assert.equal(previewLimit(360,260),92);
assert.equal(previewLimit(200,260),0);
assert.equal(clampPreviewPosition(-50,92),0);
assert.equal(clampPreviewPosition(150,92),92);
assert.equal(clampPreviewPosition(42,92),42);
assert.equal(clampPreviewPosition(Number.NaN,92),0);
const preview=fs.readFileSync('src/components/FloatingHoldingCardPreview.tsx','utf8');
const editor=fs.readFileSync('src/components/PageFrameSettingsModal.tsx','utf8');
const workbench=fs.readFileSync('src/components/PageLayoutToolWorkbench.tsx','utf8');
const card=fs.readFileSync('src/components/HoldingQuoteModule.tsx','utf8');
assert.match(preview,/<HoldingQuoteModule badgeConfig=\{badgeConfig\} item=\{item\} wallConfig=\{config\} style=\{style\} layout=\{layout\}/,'Whole-card preview reuses current renderer and includes editable ETF badges');
assert.match(editor,/PageLayoutToolWorkbench/);
assert.match(workbench,/wallConfig=\{wall\}/);
assert.match(workbench,/layoutEditMode layoutSelectionId=\{frameKey===item\.key\?selection\.id:null\}/);\nassert.match(workbench,/onLayoutSelect=\{\(id,label\)=>\{setFrameKey\(item\.key\);selectHolding\(id,label\);\}\}/);
assert.ok(!workbench.includes('NT$ 123,456'),'layout preview must not use fabricated dashboard data');
assert.match(card,/groups\.footer/);
assert.ok(!preview.includes('items.map('),'preview must not render an entire wall');
console.log('V2.1.3 preview renderer remains reusable; page layout tool now binds the real card renderer and live draft without fabricated values: PASS');
