const fs=require('node:fs');
const assert=require('node:assert/strict');
const read=p=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const app=JSON.parse(read('app.json'));
const settings=read('src/screens/SettingsScreen.tsx');
const ledger=read('src/screens/LedgerScreen.tsx');
const calendar=read('src/dividend/dividendCalendar.ts');
const dividend=read('src/screens/DividendScreen.tsx');
const prefs=read('src/settings/SettingsRuntime.tsx');
const backup=read('src/settings/BackupService.ts');
const ci=read('.github/workflows/ci.yml');
assert.equal(pkg.version,'2.1.21');
assert.equal(app.expo.version,'2.1.21');
assert.equal(app.expo.android.versionCode,20121);
assert.equal(app.expo.android.package,'com.tfasset.app');
assert.match(settings,/const VERSION='2\.1\.21'/);
assert.match(settings,/const BUILD='20121'/);
assert.match(backup,/const APP_VERSION='2\.1\.21'/);
assert.match(ci,/TF-Asset-V2\.1\.21-QA\.apk/);
assert.match(ledger,/onPress=\{\(\)=>setSelectedEntry\(row\)\}/);
assert.match(ledger,/Alert\.alert\('刪除交易紀錄？'/);
assert.match(calendar,/lastBuyDate/);
assert.match(calendar,/dateFromNote\(entry\.note,'最後購買日'\)/);
assert.match(dividend,/最後購買日/);
assert.match(prefs,/showLastBuyDate/);
for(const core of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(fs.existsSync(core),core);
console.log('V2.1.21 identity + ledger details + explicit dividend last-buy source smoke: PASS');
