import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.entranceEnabled,false,'legacy frames do not animate on open');
const fx=normalizeFrameEffects({entranceEnabled:true,entranceMode:'zoom',
 entranceDurationMs:750,entranceScale:.8,entranceDistance:40,entranceRotationDeg:30});
assert.equal(fx.entranceEnabled,true);assert.equal(fx.entranceMode,'zoom');
assert.equal(fx.entranceDurationMs,750);assert.equal(fx.entranceScale,.8);
assert.equal(fx.entranceDistance,40);assert.equal(fx.entranceRotationDeg,30);
const bad=normalizeFrameEffects({entranceEnabled:'yes',entranceMode:'fade',
 entranceDurationMs:1,entranceDistance:999,entranceScale:-1,entranceRotationDeg:0});
assert.equal(bad.entranceEnabled,false);assert.equal(bad.entranceMode,'slide');
assert.equal(bad.entranceDurationMs,200);assert.equal(bad.entranceDistance,120);
assert.equal(bad.entranceScale,.65);assert.equal(bad.entranceRotationDeg,5);
assert.equal(normalizeFrameEffects({entranceDurationMs:9999}).entranceDurationMs,2500);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(x=>x.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(new Set(all.map(x=>x.id)).size,184);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,155);assert.equal(audit.pending,29);
const tool=all.find(x=>x.id==='fx-animation-advanced')!;
assert.equal(tool.status,'ready');assert.equal(tool.field,'framefx:entranceEnabled');
assert.equal(resolveSkillAdapter(tool,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tool,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),ui=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('const entrance=useRef(new Animated.Value(1)).current'));
assert.ok(card.includes("if(!editorStyle||!fx.entranceEnabled||reduceMotion)return"));
assert.ok(card.includes('easing:Easing.out(Easing.cubic)')&&card.includes('useNativeDriver:true'));
assert.ok(card.includes("fx.entranceMode==='slide'")&&card.includes("fx.entranceMode==='zoom'"));
assert.ok(card.includes("fx.entranceRotationDeg+'deg'")&&card.includes('return <Animated.View style={['));
assert.ok(card.includes('editorStyle&&fx.entranceEnabled&&!reduceMotion&&{transform:entranceTransform}'));
assert.ok(card.includes("AccessibilityInfo.addEventListener('reduceMotionChanged'")&&card.includes('subscription.remove()'));
assert.ok(card.includes('animation.stop();entrance.stopAnimation();entrance.setValue(1)'));
assert.ok(ui.includes("if(key==='entranceEnabled')")&&ui.includes('entranceMode')&&ui.includes('entranceDurationMs'));
assert.ok(ui.includes('entranceDistance')&&ui.includes('entranceScale')&&ui.includes('entranceRotationDeg'));
assert.ok(ui.includes('maintenance.patchFrame'));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.29');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30029);assert.equal(app.expo.ios.buildNumber,'30029');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.29-QA.apk')&&wf.includes('npm run test:v3_0_29'));
assert.ok(wf.includes("startsWith(github.head_ref, 'go-v3.0.')"));
assert.ok(read('src/screens/SettingsScreen.tsx').includes("const BUILD='30029'"));
for(const p of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(p).length>0);
console.log('V3.0.29 native frame entrance + Reduce Motion regression PASS; 155 wired /29 pending; device testing separate');
