import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {formatDisplayNumber,DISPLAY_UNITS} from '../src/maintenance/numberDisplay';
import {normalizeTargetOverride,targetToolSupported,TARGET_APPEARANCE,resetTargetVisualOverride} from '../src/maintenance/inspectionModel';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DISPLAY_UNITS.length,5);
assert.equal(formatDisplayNumber('NT$ 1,234,567','ten-thousand',2),'NT$ 123.46萬');
assert.equal(formatDisplayNumber('-1,234,000','thousand',2),'-1,234.00千');
assert.equal(formatDisplayNumber('5000000','million',1),'5.0百萬');
assert.equal(formatDisplayNumber('NT$ 1,234.56','yuan',1),'NT$ 1,234.6');
assert.equal(formatDisplayNumber('1234','original',2),'1234');
for(const val of ['待核對','載入中','0050','14.5%','12/31','NaN','1e100','42 元'])
 assert.equal(formatDisplayNumber(val,'ten-thousand',2),val);
assert.equal(formatDisplayNumber('2330','thousand',2,true),'2330','plain code-like Text must remain original');
assert.equal(formatDisplayNumber('1234','thousand',2),'1.23千','a true metric amount still formats');
assert.equal(formatDisplayNumber('100000000000000000','million',2),'100000000000000000');
assert.deepEqual(normalizeTargetOverride({displayUnit:'million',displayDigits:8,actual_fee:900,tax:25}),{displayUnit:'million',displayDigits:4});
assert.deepEqual(normalizeTargetOverride({displayUnit:'invalid',displayDigits:NaN}),{});
assert.equal(TARGET_APPEARANCE.displayUnit,'original');assert.equal(TARGET_APPEARANCE.displayDigits,0);
assert.deepEqual(resetTargetVisualOverride({displayUnit:'million',displayDigits:2,visible:false}),{visible:false});
for(const kind of ['metric','value'] as const)assert.equal(targetToolSupported(kind,'target:numberFormat'),true);
for(const kind of ['frame','text','prefix','control','wall'] as const)assert.equal(targetToolSupported(kind,'target:numberFormat'),false);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(g=>g.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,164);assert.equal(audit.pending,20);
const units=all.find(t=>t.id==='units')!;assert.equal(units.field,'target:numberFormat');assert.equal(units.status,'ready');
assert.equal(resolveSkillAdapter(units,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(units,{scope:'target',kind:'control',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const metric=read('src/components/MetricTile.tsx'),stack=read('src/components/PageEditorStack.tsx');
const panel=read('src/maintenance/MaintenanceWorkbench.tsx'),rt=read('src/maintenance/MaintenanceRuntime.tsx');
assert.ok(metric.includes('formatDisplayNumber(value,editorStyle.displayUnit,editorStyle.displayDigits??0)'));
assert.ok(stack.includes('formatDisplayNumber(content,appearance.displayUnit,appearance.displayDigits,true)'));
assert.ok(panel.includes("fieldName==='numberFormat'")&&panel.includes("maint.patchTarget(target.id,{displayUnit:item.id})")&&panel.includes("maint.patchTarget(target.id,{displayDigits:digits})"));
assert.ok(rt.includes('normalizeTargetOverride(override)')&&rt.includes('draftTargets'));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.39');assert.equal(app.expo.version,'3.0.39');
assert.equal(app.expo.android.versionCode,30039);assert.equal(app.expo.ios.buildNumber,'30039');
const wf=read('.github/workflows/ci.yml');assert.ok(wf.includes('TF-Asset-V3.0.39-QA.apk')&&wf.includes('npm run test:v3_0_39'));
for(const path of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(path).length>0);
console.log('V3.0.39 formatter behavioral, AB runtime connection, immutable core and identity gates PASS; device separate');
