import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {nextMetricTapEmphasis} from '../src/maintenance/metricTap';
import {normalizeTargetOverride,targetToolSupported,TARGET_APPEARANCE,resetTargetVisualOverride} from '../src/maintenance/inspectionModel';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
const read=(p:string)=>readFileSync(p,'utf8');
// Real native metric tap toggles a local visual state, never source amounts.
assert.equal(nextMetricTapEmphasis(false,'emphasize'),true);
assert.equal(nextMetricTapEmphasis(true,'emphasize'),false);
assert.equal(nextMetricTapEmphasis(true,'none'),false);
assert.equal(TARGET_APPEARANCE.tapAction,'none','old installs remain noninteractive');
assert.deepEqual(normalizeTargetOverride({tapAction:'emphasize',actual_fee:88,tax:15}),{tapAction:'emphasize'});
assert.deepEqual(normalizeTargetOverride({tapAction:'open-ledger'}),{});
assert.deepEqual(resetTargetVisualOverride({tapAction:'emphasize',fontSize:21}),{tapAction:'emphasize'},'visual reset never resets a native action');
assert.equal(targetToolSupported('metric','target:tapAction'),true);
for(const kind of ['value','frame','text','prefix','control','wall'] as const)
 assert.equal(targetToolSupported(kind,'target:tapAction'),false);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(g=>g.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,161);assert.equal(audit.pending,23);
const tap=all.find(t=>t.id==='tap')!;
assert.equal(tap.status,'ready');assert.equal(tap.field,'target:tapAction');
assert.equal(resolveSkillAdapter(tap,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tap,{scope:'target',kind:'value',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const metric=read('src/components/MetricTile.tsx'),stack=read('src/components/PageEditorStack.tsx');
const inspect=read('src/maintenance/InspectableTarget.tsx'),panel=read('src/maintenance/MaintenanceWorkbench.tsx');
assert.ok(metric.includes('<Pressable disabled={!tapEnabled}')&&metric.includes('nextMetricTapEmphasis(previous,editorStyle?.tapAction'));
assert.ok(metric.includes('tapEnabled&&(emphasized||previewTap)')&&metric.includes('setEmphasized(false)'));
assert.ok(stack.includes('previewTap={render.editing}'));assert.ok(inspect.includes('editing};'));
assert.ok(panel.includes("fieldName==='tapAction'")&&panel.includes("maint.patchTarget(target.id,{tapAction:action})"));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.36');assert.equal(app.expo.version,'3.0.36');
assert.equal(app.expo.android.versionCode,30036);assert.equal(app.expo.ios.buildNumber,'30036');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.36-QA.apk')&&wf.includes('npm run test:v3_0_35'));
for(const f of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(f).length>0);
console.log('V3.0.36 metric native tap action + AB preview behavior + immutable boundaries: AUTOMATED PASS; device validation pending');
