import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,frameShadowSpreadBands} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.shadowSpreadEnabled,false,'legacy and default frames must remain unchanged');
const fx=normalizeFrameEffects({shadowSpreadEnabled:true,shadowSpreadRadius:24,shadowSpreadLayers:3,shadowSpreadOpacity:.6});
assert.equal(fx.shadowSpreadEnabled,true);assert.equal(fx.shadowSpreadRadius,24);
assert.equal(fx.shadowSpreadLayers,3);assert.equal(fx.shadowSpreadOpacity,.6);
const capped=normalizeFrameEffects({shadowSpreadEnabled:'on',shadowSpreadRadius:500,shadowSpreadLayers:99,shadowSpreadOpacity:9});
assert.equal(capped.shadowSpreadEnabled,false);assert.equal(capped.shadowSpreadRadius,32);
assert.equal(capped.shadowSpreadLayers,6);assert.equal(capped.shadowSpreadOpacity,.65);
assert.equal(normalizeFrameEffects({shadowSpreadLayers:2.6}).shadowSpreadLayers,3);
assert.deepEqual(frameShadowSpreadBands(0,.6,4),[]);
assert.deepEqual(frameShadowSpreadBands(24,0,4),[]);
const bands=frameShadowSpreadBands(24,.6,3);
assert.equal(bands.length,3);assert.equal(bands[0]?.inset,8);assert.equal(bands[2]?.inset,24);
assert.ok(bands[0]!.alpha>bands[1]!.alpha&&bands[1]!.alpha>bands[2]!.alpha);
assert.ok(frameShadowSpreadBands(100,10,100).length<=6);
const audit=completeCatalogAudit(),all=COMPLETE_ENGINEER_SKILLS.flatMap(x=>x.tools);
assert.equal(all.length,184);assert.equal(new Set(all.map(x=>x.id)).size,184);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,156);assert.equal(audit.pending,28);
const tool=all.find(x=>x.id==='fx-shadow-spread')!;
assert.equal(tool.field,'framefx:shadowSpreadEnabled');assert.equal(tool.status,'ready');
assert.equal(resolveSkillAdapter(tool,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tool,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),ui=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('frameShadowSpreadBands(fx.shadowSpreadRadius,fx.shadowSpreadOpacity,fx.shadowSpreadLayers)'));
assert.ok(card.includes('shadowSpreadOn?frameShadowSpreadBands('));
assert.ok(card.includes('pointerEvents="none"')&&card.includes('colorWithAlpha(shadowColor,band.alpha)'));
assert.ok(card.includes("outerGlowOn||shadowSpreadOn||borderGradientOn?{overflow:'visible' as const}"));
assert.ok(ui.includes("if(key==='shadowSpreadEnabled')")&&ui.includes('shadowSpreadLayers')&&ui.includes('shadowSpreadOpacity'));
assert.ok(ui.includes('ColorPalettePicker')&&ui.includes('maintenance.patchFrame'));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.30');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30030);assert.equal(app.expo.ios.buildNumber,'30030');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.30-QA.apk')&&wf.includes('npm run test:v3_0_30'));
assert.ok(wf.includes("startsWith(github.head_ref, 'go-v3.0.')"));
assert.ok(read('src/screens/SettingsScreen.tsx').includes("const BUILD='30030'"));
for(const p of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(p).length>0);
console.log('V3.0.30 shadow spread native adapter regression PASS; 184 skills / 156 wired / 28 pending (device separate)');
