import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {TARGET_APPEARANCE,normalizeTargetOverride,targetToolSupported} from '../src/maintenance/inspectionModel';
import {ENGINEER_SKILLS} from '../src/maintenance/skillTree';
const normalized=normalizeTargetOverride({positionX:111,positionY:-54,labelProfitColor:true,backgroundProfitColor:true,borderProfitColor:true});
assert.equal(normalized.positionX,111);assert.equal(normalized.positionY,-54);
assert.equal(normalized.backgroundProfitColor,true);assert.equal(normalized.borderProfitColor,true);
assert.equal(TARGET_APPEARANCE.positionX,0);assert.equal(TARGET_APPEARANCE.positionY,0);
assert.ok(targetToolSupported('metric','target:positionX')&&targetToolSupported('value','target:positionY'));
assert.ok(!targetToolSupported('value','target:labelText'),'business values remain read only');
assert.equal(ENGINEER_SKILLS.length,16);
const read=(p:string)=>readFileSync(p,'utf8');
const dock=read('src/maintenance/MaintenanceWorkbench.tsx');
assert.ok(dock.includes('<CoordinateControl')&&dock.includes("value+n")&&dock.includes('number-origin'));
assert.ok(!dock.includes('輸入色碼'));
assert.ok(dock.includes('ColorPalettePicker')&&dock.includes('onProfitColorChange'));
const target=read('src/maintenance/InspectableTarget.tsx');
assert.ok(target.includes('onLayout={measure}')&&target.includes('translateX:appearance.positionX'));
assert.ok(target.includes("minWidth:136"),'V3.0.3 signed-off responsive layout must be retained');
const frame=read('src/components/FrameCard.tsx');
assert.ok(frame.includes("left:'50%'")&&frame.includes("top:'50%'"),'workspace axis guidelines must be visible');
const metric=read('src/components/MetricTile.tsx');
assert.ok(metric.includes('backgroundProfitColor')&&metric.includes('borderProfitColor')&&metric.includes('labelProfitColor'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.4');assert.equal(app.expo.version,'3.0.4');assert.equal(app.expo.android.versionCode,30004);
console.log('V3.0.4 real XY offsets, manual coordinate and 1-dp buttons, independent profit-linked palette gates: PASS');
