import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,outerGlowLayers} from '../src/maintenance/frameEffects';
import {frameVisualSnapshot,restoreFrameVisual} from '../src/maintenance/visualHistory';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import type {FrameEditorConfig} from '../src/editor/editorModel';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.outerGlowEnabled,false);
const fx=normalizeFrameEffects({outerGlowEnabled:true,outerGlowColor:'#abc123',outerGlowProfitColor:true,
 outerGlowOpacity:.6,outerGlowSpread:12,outerGlowSoftness:35,actual_fee:300});
assert.equal(fx.outerGlowColor,'#ABC123');assert.equal(fx.outerGlowProfitColor,true);
assert.equal(fx.outerGlowOpacity,.6);assert.equal(fx.outerGlowSpread,12);assert.equal(fx.outerGlowSoftness,35);
assert.equal('actual_fee' in fx,false);
const capped=normalizeFrameEffects({outerGlowOpacity:99,outerGlowSpread:99,outerGlowSoftness:-4,
 outerGlowColor:'NOT_HEX',outerGlowEnabled:'yes'});
assert.equal(capped.outerGlowOpacity,.8);assert.equal(capped.outerGlowSpread,32);
assert.equal(capped.outerGlowSoftness,0);assert.equal(capped.outerGlowColor,DEFAULT_FRAME_EFFECTS.outerGlowColor);
assert.equal(capped.outerGlowEnabled,false);
assert.equal(outerGlowLayers(1,12,0).length,0);
const rings=outerGlowLayers(4,25,.7);
assert.ok(rings.length>=3&&rings.length<=8&&rings[0]!.inset>rings[rings.length-1]!.inset);
assert.ok(rings.every(layer=>layer.alpha>0&&layer.alpha<=.8&&layer.borderWidth>0));
const snap=frameVisualSnapshot({effects:fx} as unknown as FrameEditorConfig);
assert.equal((snap.effects as typeof fx).outerGlowColor,'#ABC123');
const restored=restoreFrameVisual({visible:false,effects:normalizeFrameEffects({})} as unknown as FrameEditorConfig,snap);
assert.equal(normalizeFrameEffects(restored.effects).outerGlowEnabled,true);
assert.equal(restored.visible,false);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(s=>s.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,149);assert.equal(audit.pending,35);
const tool=all.find(t=>t.id==='fx-outer-glow')!;
assert.equal(tool.status,'ready');assert.equal(tool.field,'framefx:outerGlowEnabled');
assert.equal(resolveSkillAdapter(tool,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tool,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const panel=read('src/maintenance/FrameEffectsToolDetails.tsx'),native=read('src/components/FrameCard.tsx');
assert.ok(panel.includes("if(key==='outerGlowEnabled')")&&panel.includes('outerGlowProfitColor'));
assert.ok(native.includes('outerGlowLayers(')&&native.includes('pointerEvents="none"')&&native.includes("overflow:'visible' as const"));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.23');assert.equal(app.expo.version,'3.0.23');
assert.equal(app.expo.android.versionCode,30023);assert.equal(app.expo.ios.buildNumber,'30023');
assert.ok(read('.github/workflows/ci.yml').includes('TF-Asset-V3.0.23-QA.apk'));
for(const p of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(p).length>0);
console.log('V3.0.23 frame native outer glow: sanitizer/layers/AB/backup/version tests PASS');
console.log('184 central skills / 149 wired declarations / 35 pending, phone visual testing separate');
