import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,colorWithAlpha} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(p:string)=>readFileSync(p,'utf8');
// Actual native frame effect, NOT a mock panel or financial value animation.
assert.equal(DEFAULT_FRAME_EFFECTS.blinkEnabled,false,'old app and saved frames must remain static');
const fx=normalizeFrameEffects({blinkEnabled:true,blinkColor:'#abC123',blinkProfitColor:true,blinkOpacity:.4,blinkPeriodMs:1200});
assert.equal(fx.blinkEnabled,true);assert.equal(fx.blinkColor,'#ABC123');
assert.equal(fx.blinkProfitColor,true);assert.equal(fx.blinkOpacity,.4);assert.equal(fx.blinkPeriodMs,1200);
const capped=normalizeFrameEffects({blinkEnabled:'yes',blinkColor:'invalid',blinkOpacity:5,blinkPeriodMs:100});
assert.equal(capped.blinkEnabled,false);assert.equal(capped.blinkColor,DEFAULT_FRAME_EFFECTS.blinkColor);
assert.equal(capped.blinkOpacity,.8);assert.equal(capped.blinkPeriodMs,500);
assert.equal(normalizeFrameEffects({blinkPeriodMs:999999}).blinkPeriodMs,5000);
assert.equal(normalizeFrameEffects({blinkEnabled:true}).blinkEnabled,true);
assert.equal(normalizeFrameEffects({}).blinkEnabled,false);
assert.equal(colorWithAlpha(fx.blinkColor,fx.blinkOpacity),'rgba(171,193,35,0.400)');
const all=COMPLETE_ENGINEER_SKILLS.flatMap(section=>section.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(new Set(all.map(t=>t.id)).size,184);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,152);assert.equal(audit.pending,32);
const blink=all.find(x=>x.id==='blink')!;
assert.equal(blink.field,'framefx:blinkEnabled');assert.equal(blink.status,'ready');
assert.equal(resolveSkillAdapter(blink,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(blink,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter','do not claim unsupported target native adapters');
const card=read('src/components/FrameCard.tsx'),ui=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('fx.blinkEnabled&&editorStyle?<Animated.View'));
assert.ok(card.includes('if(!editorStyle||!fx.blinkEnabled||reduceMotion)return'));
assert.ok(card.includes('useNativeDriver:true')&&card.includes('blink.stopAnimation()'));
assert.ok(card.includes('pointerEvents="none"')&&card.includes('opacity:blink'));
assert.ok(card.includes('colorWithAlpha(blinkColor,fx.blinkOpacity)'));
assert.ok(ui.includes("if(key==='blinkEnabled')")&&ui.includes('blinkPeriodMs')&&ui.includes('blinkProfitColor'));
assert.ok(ui.includes('ColorPalettePicker')&&ui.includes('maintenance.patchFrame'));
const backup=read('src/settings/BackupService.ts');
assert.ok(backup.includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.26');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30026);assert.equal(app.expo.ios.buildNumber,'30026');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes("branches: [main, 'go-v3.0.*']")&&wf.includes("startsWith(github.head_ref, 'go-v3.0.')"));
assert.ok(wf.includes('TF-Asset-V3.0.26-QA.apk')&&wf.includes('npm run test:v3_0_26'));
assert.ok(read('src/screens/SettingsScreen.tsx').includes("const VERSION='3.0.26'"));
for(const path of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(path).length>0);
console.log('V3.0.26 native frame blink regression PASS: A/B/C, normalized effects, reduced motion, financial isolation, APK gates');
console.log('184 central skills / 152 declared wired / 32 pending / Android device validation separate');
