import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,DEFAULT_FRAME_TOUCH_STATE,applyFrameTouchAction} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(path:string)=>readFileSync(path,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.frameInteractionEnabled,false,'legacy frames must have no new gestures');
assert.equal(DEFAULT_FRAME_EFFECTS.frameTapAction,'emphasize');
assert.equal(DEFAULT_FRAME_EFFECTS.frameLongAction,'collapse');
const valid=normalizeFrameEffects({frameInteractionEnabled:true,frameTapAction:'collapse',frameLongAction:'emphasize'});
assert.equal(valid.frameInteractionEnabled,true);
assert.equal(valid.frameTapAction,'collapse');
assert.equal(valid.frameLongAction,'emphasize');
const rejected=normalizeFrameEffects({frameInteractionEnabled:'true',frameTapAction:'delete',frameLongAction:'launch-app'});
assert.equal(rejected.frameInteractionEnabled,false);
assert.equal(rejected.frameTapAction,'emphasize');
assert.equal(rejected.frameLongAction,'collapse');
const marked=applyFrameTouchAction(DEFAULT_FRAME_TOUCH_STATE,'emphasize');
assert.deepEqual(marked,{emphasized:true,collapsed:false});
assert.deepEqual(applyFrameTouchAction(marked,'emphasize'),DEFAULT_FRAME_TOUCH_STATE);
const hidden=applyFrameTouchAction(marked,'collapse');
assert.deepEqual(hidden,{emphasized:true,collapsed:true});
assert.deepEqual(applyFrameTouchAction(hidden,'collapse'),marked);
assert.equal(applyFrameTouchAction(hidden,'none'),hidden);
assert.equal(applyFrameTouchAction(hidden,'emphasize',true),hidden,'long press must suppress tap');
const audit=completeCatalogAudit(),all=COMPLETE_ENGINEER_SKILLS.flatMap(s=>s.tools);
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,157);assert.equal(audit.pending,27);
const interaction=all.find(t=>t.id==='fx-frame-interaction');
assert.ok(interaction);assert.equal(interaction!.status,'ready');
assert.equal(interaction!.field,'framefx:frameInteractionEnabled');
assert.equal(resolveSkillAdapter(interaction!,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(interaction!,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),panel=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('<Pressable disabled={!editorStyle||!fx.frameInteractionEnabled}'));
assert.ok(card.includes('onLongPress={()=>')&&card.includes('longPressConsumed.current=true'));
assert.ok(card.includes('if(longPressConsumed.current){longPressConsumed.current=false;return;}'));
assert.ok(card.includes('applyFrameTouchAction(previous,fx.frameTapAction)'));
assert.ok(card.includes('frameTouch.collapsed&&fx.frameInteractionEnabled?null'));
assert.ok(card.includes('{action}')&&card.includes('pointerEvents="none"'));
assert.ok(panel.includes("if(key==='frameInteractionEnabled')")&&panel.includes('frameTapAction')&&panel.includes('frameLongAction'));
assert.ok(panel.includes('maintenance.patchFrame({effects:normalizeFrameEffects('));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.32');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30032);assert.equal(app.expo.ios.buildNumber,'30032');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.32-QA.apk')&&wf.includes('npm run test:v3_0_32'));
assert.ok(wf.includes("github.head_ref == 'go-v3.0.32-20260927-native-frame-interaction'"));
for(const file of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])
  assert.ok(read(file).length>0,'immutable finance boundary: '+file);
console.log('V3.0.32 frame header native gestures, isolated tap/long-press, draft/restore wiring, 184/157/27: AUTOMATED PASS; device validation pending');
