import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {metricThresholdMatches} from '../src/maintenance/metricThreshold';
import {normalizeTargetOverride,resetTargetVisualOverride,targetToolSupported,TARGET_APPEARANCE} from '../src/maintenance/inspectionModel';
import {completeCatalogAudit,COMPLETE_ENGINEER_SKILLS} from '../src/maintenance/fullSkillCatalog';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(metricThresholdMatches('NT$ 1,234.5',true,1200,'gte'),true);
assert.equal(metricThresholdMatches('−123.5',true,-100,'lte'),true);
assert.equal(metricThresholdMatches('12.3',true,13,'gte'),false);
assert.equal(metricThresholdMatches('12.3',true,13,'lte'),true);
for(const raw of ['0050','00878','12.3%','載入中','1,00','NT$ NaN',''])assert.equal(metricThresholdMatches(raw,true,0,'gte'),false,raw);
assert.equal(metricThresholdMatches('123',false,0,'gte'),false,'default OFF');
assert.equal(metricThresholdMatches('123',true,Number.NaN,'gte'),false);
assert.equal(TARGET_APPEARANCE.thresholdEnabled,false);
assert.deepEqual(normalizeTargetOverride({thresholdEnabled:true,thresholdValue:50.25,thresholdOperator:'lte',actual_fee:88,tax:15}),
  {thresholdValue:50.25,thresholdEnabled:true,thresholdOperator:'lte'});
assert.deepEqual(normalizeTargetOverride({thresholdEnabled:'yes',thresholdValue:Infinity,thresholdOperator:'sell'}),{});
assert.deepEqual(resetTargetVisualOverride({thresholdEnabled:true,thresholdValue:2,fontSize:20}),{},'reset removes visual-only threshold');
assert.equal(targetToolSupported('metric','target:threshold'),true);
for(const kind of ['value','frame','text','prefix','control','wall'] as const)
 assert.equal(targetToolSupported(kind,'target:threshold'),false);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(g=>g.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,163);assert.equal(audit.pending,21);
const threshold=all.find(t=>t.id==='threshold')!;
assert.equal(threshold.status,'ready');assert.equal(threshold.field,'target:threshold');
assert.equal(resolveSkillAdapter(threshold,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(threshold,{scope:'target',kind:'value',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const metric=read('src/components/MetricTile.tsx'),panel=read('src/maintenance/MaintenanceWorkbench.tsx');
assert.ok(metric.includes('metricThresholdMatches(value,editorStyle?.thresholdEnabled'));
assert.ok(metric.includes('(thresholdMatched||tapEnabled&&'));
assert.ok(panel.includes("fieldName==='threshold'")&&panel.includes('maint.patchTarget(target.id,{thresholdEnabled:value})'));
assert.ok(panel.includes("maint.patchTarget(target.id,{thresholdValue:number})"));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.38');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30038);assert.equal(app.expo.ios.buildNumber,'30038');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.38-QA.apk')&&wf.includes('npm run test:v3_0_38'));
for(const file of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(file).length>0);
console.log('V3.0.38 native metric visual threshold behavior: automated PASS; Android device pending');
