import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,responsiveFrameDensity} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.responsiveEnabled,false,'old frames must preserve original density');
const fx=normalizeFrameEffects({responsiveEnabled:true,responsiveCompactWidth:500,responsiveDenseWidth:350});
assert.equal(fx.responsiveEnabled,true);assert.equal(fx.responsiveCompactWidth,500);assert.equal(fx.responsiveDenseWidth,350);
const bad=normalizeFrameEffects({responsiveEnabled:'yes',responsiveCompactWidth:1,responsiveDenseWidth:999});
assert.equal(bad.responsiveEnabled,false);assert.equal(bad.responsiveCompactWidth,360);
assert.equal(bad.responsiveDenseWidth,320,'dense threshold must be 40dp below compact');
assert.equal(normalizeFrameEffects({responsiveCompactWidth:9999,responsiveDenseWidth:-2}).responsiveCompactWidth,900);
assert.equal(normalizeFrameEffects({responsiveDenseWidth:-2}).responsiveDenseWidth,240);
assert.equal(responsiveFrameDensity(800,'standard',500,350),'standard');
assert.equal(responsiveFrameDensity(500,'standard',500,350),'compact');
assert.equal(responsiveFrameDensity(350,'standard',500,350),'dense');
assert.equal(responsiveFrameDensity(400,'compact',500,350),'compact');
assert.equal(responsiveFrameDensity(300,'compact',500,350),'dense');
assert.equal(responsiveFrameDensity(800,'dense',500,350),'dense','never widen explicit density');
assert.equal(responsiveFrameDensity(0,'standard',500,350),'standard','before native measure retain base');
assert.equal(responsiveFrameDensity(NaN,'compact',500,350),'compact');
assert.equal(responsiveFrameDensity(380,'standard',400,390),'compact','malformed threshold ordered safely');
const all=COMPLETE_ENGINEER_SKILLS.flatMap(x=>x.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(new Set(all.map(x=>x.id)).size,184);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);assert.equal(audit.readyDeclared,156);assert.equal(audit.pending,28);
const tool=all.find(x=>x.id==='breakpoint')!,globalTool=all.find(x=>x.id==='fx-responsive')!;
assert.equal(tool.field,'framefx:responsiveEnabled');assert.equal(tool.status,'ready');
assert.equal(globalTool.status,'adapter-required','cross-page template integration is not done');
assert.equal(resolveSkillAdapter(tool,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tool,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),ui=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('responsiveFrameDensity(measuredFrameWidth,layout,fx.responsiveCompactWidth,fx.responsiveDenseWidth)'));
assert.ok(card.includes('setMeasuredFrameWidth(previous=>Math.abs(previous-width)<1?previous:width)'));
assert.ok(card.includes('responsiveDensity')&&card.includes('styles.cardCompact')&&card.includes('styles.cardDense'));
assert.ok(card.includes('responsiveDensity===')&&card.includes('styles.titleDense'));
assert.ok(card.includes('return <Animated.View style={[')&&card.includes('onLayout={(event:LayoutChangeEvent)=>'));
assert.ok(ui.includes("if(key==='responsiveEnabled')")&&ui.includes('responsiveCompactWidth')&&ui.includes('responsiveDenseWidth'));
assert.ok(ui.includes('maintenance.patchFrame'));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.31');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30031);assert.equal(app.expo.ios.buildNumber,'30031');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.31-QA.apk')&&wf.includes('npm run test:v3_0_31'));
assert.ok(wf.includes("startsWith(github.head_ref, 'go-v3.0.')"));
assert.ok(read('src/screens/SettingsScreen.tsx').includes("const BUILD='30031'"));
for(const p of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(p).length>0);
console.log('V3.0.31 measured frame breakpoints regression PASS: 184 skills / 156 wired / 28 pending; device testing separate');
