import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {metricSwipeExceeded,nextMetricTapEmphasis} from '../src/maintenance/metricTap';
import {normalizeTargetOverride,TARGET_APPEARANCE,targetToolSupported,resetTargetVisualOverride} from '../src/maintenance/inspectionModel';
import {completeCatalogAudit,COMPLETE_ENGINEER_SKILLS} from '../src/maintenance/fullSkillCatalog';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
const read=(p:string)=>readFileSync(p,'utf8');
const origin={x:100,y:100};
assert.equal(metricSwipeExceeded(origin,{x:110,y:108}),false,'short movement is tap');
assert.equal(metricSwipeExceeded(origin,{x:113,y:100}),true,'horizontal swipe cancels native tap');
assert.equal(metricSwipeExceeded(origin,{x:100,y:113}),true,'vertical scroll cancels native tap');
assert.equal(metricSwipeExceeded(origin,{x:112,y:112}),false,'boundary is not exceeded');
assert.equal(metricSwipeExceeded(null,{x:999,y:999}),false,'no touch origin is not a swipe');
assert.equal(nextMetricTapEmphasis(false,'emphasize'),true);
assert.equal(nextMetricTapEmphasis(true,'none'),false);
assert.equal(TARGET_APPEARANCE.tapSwipeGuard,true,'existing installs default to safe swipe exclusion');
assert.deepEqual(normalizeTargetOverride({tapSwipeGuard:false,actual_fee:12,tax:3}),{tapSwipeGuard:false});
assert.deepEqual(normalizeTargetOverride({tapSwipeGuard:'off'}),{});
assert.deepEqual(resetTargetVisualOverride({tapSwipeGuard:false,fontSize:20}),{tapSwipeGuard:false});
assert.equal(targetToolSupported('metric','target:tapSwipeGuard'),true);
for(const kind of ['value','text','frame','prefix','control','wall'] as const)
 assert.equal(targetToolSupported(kind,'target:tapSwipeGuard'),false);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(g=>g.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,161);assert.equal(audit.pending,23);
const swipe=all.find(t=>t.id==='swipe')!;
assert.equal(swipe.status,'ready');assert.equal(swipe.field,'target:tapSwipeGuard');
assert.equal(resolveSkillAdapter(swipe,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(swipe,{scope:'target',kind:'frame',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const metric=read('src/components/MetricTile.tsx'),panel=read('src/maintenance/MaintenanceWorkbench.tsx');
assert.ok(metric.includes('onTouchStart=')&&metric.includes('onTouchMove=')&&metric.includes('onTouchCancel='));
assert.ok(metric.includes('guardEnabled&&swipeConsumed.current'));
assert.ok(metric.includes('metricSwipeExceeded(start.current'));
assert.ok(panel.includes("fieldName==='tapSwipeGuard'")&&panel.includes('maint.patchTarget(target.id,{tapSwipeGuard:value})'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.36');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30036);assert.equal(app.expo.ios.buildNumber,'30036');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.36-QA.apk')&&wf.includes('npm run test:v3_0_36'));
for(const file of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(file).length>0);
console.log('V3.0.36 native metric tap/swipe exclusion behavior PASS; Android device testing pending');
