import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {AB_PROPERTY_GROUPS,AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {COMPLETE_ENGINEER_SKILLS,FULL_SKILL_SECTIONS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
const read=(p:string)=>readFileSync(p,'utf8');
const wb=read('src/maintenance/MaintenanceWorkbench.tsx'),audit=completeCatalogAudit();
assert.equal(FULL_SKILL_SECTIONS.length,6,'legacy taxonomy remains internal only');
assert.equal(COMPLETE_ENGINEER_SKILLS.length,30);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.existing,169);assert.equal(audit.advanced,12);assert.equal(audit.unregistered,3);
assert.deepEqual(AB_PROPERTY_GROUPS.slice(0,3).map(g=>g.label),['長度','寬度','顏色']);
assert.ok(!wb.includes('FULL_SKILL_SECTIONS.map'),'V3.0.15 extra navigation level eliminated');
assert.ok(wb.includes('searchAbProperties(query)')&&wb.includes('visibleB.map(group=><Pressable'));
assert.ok(wb.includes('C｜開啟損益色')&&wb.includes('C｜開啟漸層'));
assert.ok(wb.includes('setOpenC(null)'),'changing B closes its old C');
assert.ok(wb.includes('maintenance.apply()')&&wb.includes('maintenance.cancel()'));
assert.ok(!wb.includes('showStats'),'do not stack a technical inventory on the mobile editor');
const app=JSON.parse(read('app.json')),pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'3.0.17');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30017);
console.log('V3.0.15 compact-layout regression migrated to the corrected A→B property→C controls: PASS');
