import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DEFAULT_FRAME_EFFECTS,normalizeFrameEffects,frameTitleMarqueeDuration} from '../src/maintenance/frameEffects';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
const read=(p:string)=>readFileSync(p,'utf8');
assert.equal(DEFAULT_FRAME_EFFECTS.titleMarqueeEnabled,false,'old frames never move by default');
const fx=normalizeFrameEffects({titleMarqueeEnabled:true,titleMarqueeSpeed:85,titleMarqueeGap:40});
assert.equal(fx.titleMarqueeEnabled,true);assert.equal(fx.titleMarqueeSpeed,85);assert.equal(fx.titleMarqueeGap,40);
const bad=normalizeFrameEffects({titleMarqueeEnabled:'on',titleMarqueeSpeed:999,titleMarqueeGap:-30});
assert.equal(bad.titleMarqueeEnabled,false);assert.equal(bad.titleMarqueeSpeed,180);assert.equal(bad.titleMarqueeGap,12);
assert.equal(normalizeFrameEffects({titleMarqueeSpeed:-1}).titleMarqueeSpeed,24);
assert.equal(normalizeFrameEffects({titleMarqueeGap:999}).titleMarqueeGap,80);
assert.equal(frameTitleMarqueeDuration(144,36,90),2000);
assert.equal(frameTitleMarqueeDuration(0,12,180),500);
assert.equal(frameTitleMarqueeDuration(Infinity,NaN,0),1333);
const all=COMPLETE_ENGINEER_SKILLS.flatMap(s=>s.tools),audit=completeCatalogAudit();
assert.equal(all.length,184);assert.equal(new Set(all.map(t=>t.id)).size,184);
assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,152);assert.equal(audit.pending,32);
const marquee=all.find(x=>x.id==='marquee')!;
assert.equal(marquee.field,'framefx:titleMarqueeEnabled');assert.equal(marquee.status,'ready');
assert.equal(resolveSkillAdapter(marquee,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(marquee,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),ui=read('src/maintenance/FrameEffectsToolDetails.tsx');
assert.ok(card.includes('marqueeActive=titleMarquee&&!reduceMotion'));
assert.ok(card.includes('titleIntrinsic>titleAvailable+1'),'only animate overflowing title');
assert.ok(card.includes('frameTitleMarqueeDuration(titleIntrinsic,fx.titleMarqueeGap,fx.titleMarqueeSpeed)'));
assert.ok(card.includes('Animated.loop(Animated.timing(marqueeShift'));
assert.ok(card.includes('easing:Easing.linear,useNativeDriver:true'));
assert.ok(card.includes("AccessibilityInfo.addEventListener('reduceMotionChanged'"));
assert.ok(card.includes('subscription.remove()')&&card.includes('importantForAccessibility="no-hide-descendants"'));
assert.ok(card.includes('marginRight:action?8:0')&&card.includes('{children}'));
assert.ok(ui.includes("if(key==='titleMarqueeEnabled')")&&ui.includes('titleMarqueeGap')&&ui.includes('titleMarqueeSpeed'));
assert.ok(ui.includes('maintenance.patchFrame'));
assert.ok(read('src/settings/BackupService.ts').includes('key.startsWith(PREFIX)'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.26');assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30026);assert.equal(app.expo.ios.buildNumber,'30026');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V3.0.26-QA.apk')&&wf.includes('npm run test:v3_0_26'));
assert.ok(wf.includes("startsWith(github.head_ref, 'go-v3.0.')"));
assert.ok(read('src/screens/SettingsScreen.tsx').includes("const VERSION='3.0.26'"));
for(const path of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(path).length>0);
console.log('V3.0.26 frame title marquee gates PASS; 184 skills / 152 declared wired / 32 pending; Android device validation separate');
