import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CENTRAL_COMPONENT_LIBRARY,instantiateComponent,normalizeInstances,removeEngineerOwnedInstance} from '../src/maintenance/componentLibrary';
import {VISUAL_TARGET_KEYS} from '../src/maintenance/inspectionModel';
const read=(p:string)=>readFileSync(p,'utf8');
const parent=CENTRAL_COMPONENT_LIBRARY.find(item=>item.id==='parent-frame');
assert.equal(parent?.installation,'ready');
const own=instantiateComponent('parent-frame','i-parent-1');
assert.equal(own.frameWidth,320);assert.equal(own.frameHeight,240);
const child={...instantiateComponent('text-note','i-child-1'),parentId:own.id};
const restored=normalizeInstances([own,child]);
assert.equal(restored[1]?.parentId,own.id);
assert.equal(restored[0]?.frameHeight,240);
const removed=removeEngineerOwnedInstance(restored,own.id);
assert.equal(removed.length,1);
assert.equal(removed[0]?.parentId,undefined,'removing parent rehomes children');
assert.equal(removeEngineerOwnedInstance(restored,'native-page-header').length,2);
assert.equal(normalizeInstances([{...own,createdBy:'native'}]).length,0);
const rt=read('src/maintenance/MaintenanceRuntime.tsx');
const wb=read('src/maintenance/MaintenanceWorkbench.tsx');
const inspect=read('src/maintenance/InspectableTarget.tsx');
assert.ok(rt.includes('sharedStyles:nextShared')&&rt.includes('localOnlyKeys:nextLocalOnly'));
assert.ok(rt.includes('session.sharedTouched')&&rt.includes('syncKind'),'native and added instances use unified kind-aware visual sync');
assert.ok(rt.includes('VISUAL_TARGET_KEYS.includes'),'sync only visual style fields');
assert.ok(rt.includes("syncScope:'frame'")&&rt.includes("session.syncScope==='app'"),'scope defaults to one frame; global must be explicit');
assert.ok(rt.includes("sharedKey(page,frameKey,kind,'frame')"),'same-kind frame style should resolve on every native target');
assert.ok(VISUAL_TARGET_KEYS.includes('shadowColor')&&VISUAL_TARGET_KEYS.includes('backgroundOpacity'));
assert.ok(!VISUAL_TARGET_KEYS.includes('labelText' as never)&&!VISUAL_TARGET_KEYS.includes('offsetX' as never),'content and position must never propagate');
assert.ok(wb.includes("if(tool.field==='instance:sync')")&&wb.includes('maint.setSyncSameKind'));
assert.ok(wb.includes("['frame','同框架']")&&wb.includes("['app','全 App']")&&wb.includes('maint.setSyncScope'));
assert.ok(wb.includes("item.templateId==='parent-frame'")&&wb.includes('frameHeight'));
assert.ok(wb.includes("overflow:'visible'"),'new parent must not auto-scroll children');
const card=read('src/components/FrameCard.tsx');
assert.ok(!card.includes('<ScrollView nestedScrollEnabled'),'existing parent resize bug fixed');
assert.ok(inspect.includes('target.id,target.kind'));
for(const path of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(path).length>0);
const pkg=JSON.parse(read('package.json'));const app=JSON.parse(read('app.json'));
assert.equal(pkg.version,'3.0.25');assert.equal(app.expo.version,'3.0.25');assert.equal(app.expo.android.versionCode,30025);
console.log('V3.0.17 parent frame and same-kind style synchronization: PASS');
