import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {frameResizeDimensions} from '../src/maintenance/frameResizeGesture';
import {COMPLETE_ENGINEER_SKILLS,completeCatalogAudit} from '../src/maintenance/fullSkillCatalog';
import {resolveSkillAdapter} from '../src/maintenance/skillAdapters';
import {AB_PROPERTY_TOOL_IDS} from '../src/maintenance/abPropertyModel';
const read=(path:string)=>readFileSync(path,'utf8');
assert.deepEqual(frameResizeDimensions({width:320,height:240},35,-25),{width:355,height:215});
assert.deepEqual(frameResizeDimensions({width:320.4,height:240.4},.4,.4),{width:321,height:241});
assert.deepEqual(frameResizeDimensions({width:320,height:240},-900,-900),{width:160,height:80});
assert.deepEqual(frameResizeDimensions({width:320,height:240},5000,5000),{width:1600,height:2400});
assert.equal(frameResizeDimensions({width:320,height:240},Number.NaN,5),null);
assert.equal(frameResizeDimensions({width:0,height:240},5,5),null);
const audit=completeCatalogAudit(),all=COMPLETE_ENGINEER_SKILLS.flatMap(g=>g.tools);
assert.equal(all.length,184);assert.equal(AB_PROPERTY_TOOL_IDS.length,184);
assert.equal(audit.readyDeclared,163);assert.equal(audit.pending,21);
const tool=all.find(x=>x.id==='resize-gesture')!;
assert.equal(tool.status,'ready');assert.equal(tool.field,'frame:resize-gesture');
assert.equal(resolveSkillAdapter(tool,{scope:'frame',page:'home',frameKey:'asset-dashboard'}).status,'active');
assert.equal(resolveSkillAdapter(tool,{scope:'target',kind:'metric',page:'home',frameKey:'asset-dashboard'}).status,'pending-adapter');
const card=read('src/components/FrameCard.tsx'),stack=read('src/components/PageEditorStack.tsx'),panel=read('src/maintenance/MaintenanceWorkbench.tsx');
assert.ok(card.includes('PanResponder.create')&&card.includes('workActive&&onResizePreview&&editorStyle'));
assert.ok(card.includes('onPanResponderMove')&&card.includes('resizeStart.current'));
assert.ok(card.includes('onPanResponderTerminationRequest:()=>false'));
assert.ok(stack.includes("active&&session?.scope==='frame'")&&stack.includes('engineer.patchFrame'));
assert.ok(panel.includes("tool.field==='frame:resize-gesture'")&&panel.includes('<FrameDimensionsToolDetails/>'));
const pkg=JSON.parse(read('package.json')),app=JSON.parse(read('app.json'));
assert.ok(['3.0.38','3.0.39'].includes(pkg.version));assert.equal(app.expo.version,pkg.version);
assert.equal(app.expo.android.versionCode,30038);assert.equal(app.expo.ios.buildNumber,'30038');
const wf=read('.github/workflows/ci.yml');
assert.ok(wf.includes('TF-Asset-V'+pkg.version+'-QA.apk')&&wf.includes('npm run test:v3_0_'+pkg.version.split('.')[2]));
for(const file of ['src/finance/canonicalLedger.ts','src/utils/etfCalculators.ts','docs/finance/CORE_LOCK.md'])assert.ok(read(file).length>0);
console.log('V3.0.38 live FrameCard native resize gesture and AB draft contract PASS; Android device pending');
