import assert from 'node:assert/strict';
import {marketValuationQuoteFromRow,valuationSessionActive,valuationValidUntil} from '../src/market/marketCenterViews';
import type {RuntimeQuote} from '../src/finance/financeSeed';
const now=Date.parse('2026-10-08T10:00:00+08:00');
const quote:RuntimeQuote={symbol:'0050',name:'ETF',currentPrice:100,previousClose:99,sourceQuoteAt:Date.parse('2026-10-07T13:30:00+08:00'),quality:'trade',source:'TWSE_MIS',priceType:'REALTIME_TRADE',quoteStatus:'STALE',sessionDate:'2026-10-07',sparkline:[],liquidationTradeMode:'ROUND_LOT',dividendFrequency:4};
assert.equal(marketValuationQuoteFromRow(quote,{now}),undefined,'previous-session trade must not verify current-session valuation');
assert.equal(marketValuationQuoteFromRow({...quote,sourceQuoteAt:now-600_000,sessionDate:'2026-10-08',quoteStatus:'DELAYED'},{now})?.currentPrice,100,'same-day last actual trade remains usable with delay metadata');
assert.equal(marketValuationQuoteFromRow({...quote,sourceQuoteAt:now,sessionDate:'2026-10-08',quoteStatus:'LIVE'},{now,unresolvedSymbols:['0050']}),undefined);
assert.equal(marketValuationQuoteFromRow(quote,{now:Date.parse('2026-10-08T08:30:00+08:00'),unresolvedSymbols:['0050']})?.currentPrice,100,'preopen last-session reference remains available');
assert.equal(marketValuationQuoteFromRow(quote,{now:Date.parse('2026-10-17T08:30:00+08:00')}),undefined,'reference cache age must be bounded');
assert.equal(marketValuationQuoteFromRow({...quote,sourceQuoteAt:now+120_001},{now}),undefined);
assert.equal(marketValuationQuoteFromRow({...quote,sourceQuoteAt:now,sessionDate:'2026-10-08',quality:'previous_close',priceType:'PREV_CLOSE'},{now}),undefined,'previous close cannot claim current-session valuation');
const today={...quote,sourceQuoteAt:now-60_000,sessionDate:'2026-10-08'};
for(const quoteStatus of ['STALE','OFFLINE'] as const)assert.equal(marketValuationQuoteFromRow({...today,quoteStatus},{now}),undefined);
assert.equal(marketValuationQuoteFromRow({...today,sessionDate:'2026-10-07'},{now}),undefined);
assert.equal(marketValuationQuoteFromRow({...today,quality:'bid_ask'},{now}),undefined);
const fridayClose=Date.parse('2026-10-09T13:30:00+08:00');
assert.equal(valuationValidUntil({...quote,sourceQuoteAt:fridayClose},fridayClose),Date.parse('2026-10-12T09:00:00+08:00'));
assert.equal(valuationSessionActive(Date.parse('2026-10-10T10:00:00+08:00')),false);
assert.equal(valuationSessionActive(Date.parse('2026-10-08T13:30:00+08:00')),false);
assert.equal(valuationSessionActive(Date.parse('2026-10-08T09:00:00+08:00')),true);
console.log('Valuation session / bounded reference / missing / delayed trade PASS');
