import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseTwseInstitutional} from '../src/market/twseInstitutional';
import {parseEtfNavRows,matchOfficialNavToClose} from '../src/market/officialEtfNav';
import {computeTechnicalSignals} from '../src/market/marketTechnicalSignals';
import type {DailyCandle} from '../src/market/twseDailyHistory';
const columns=['證券名稱','自營商買賣超股數','投信買賣超股數','外陸資買賣超股數(不含外資自營商)','證券代號','三大法人買賣超股數'];
const data=[['台積電','-1,000','3,000','5,000','2330','7,000']];
const record=parseTwseInstitutional({stat:'OK',date:'20261008',fields:columns,data},'2330','2026-10-08');
assert.deepEqual([record?.foreign,record?.trust,record?.dealer,record?.total],[5000,3000,-1000,7000]);
assert.equal(parseTwseInstitutional({stat:'OK',date:'20261007',fields:columns,data},'2330','2026-10-08'),null,'stale date rejected');
assert.equal(parseTwseInstitutional({stat:'OK',date:'20261008',fields:columns.slice(0,-1),data},'2330','2026-10-08'),null,'missing essential field rejects');
assert.equal(parseTwseInstitutional({stat:'OK',date:'20261008',fields:columns,data:[['台積電','--','3','5','2330','8']]},'2330','2026-10-08'),null,'-- is unavailable, not zero');
assert.equal(parseTwseInstitutional({stat:'休市',fields:columns,data},'2330','2026-10-08'),null);
const nav=parseEtfNavRows({netPrice:[{date:'2026/10/08',count:'24.21'},{date:'2026/10/07',count:'24.42'}],atmps:[{date:'2026/10/08',count:'0.45'}]});
assert.equal(nav.length,2);
const history:DailyCandle[]=[{date:'2026-10-08',open:24,high:24.4,low:23.9,close:24.32,volume:100,source:'TWSE'},
  {date:'2026-10-06',open:24,high:24.2,low:23.8,close:24.04,volume:200,source:'TWSE'}];
const matched=matchOfficialNavToClose(nav,history);
assert.equal(matched[0]?.premiumPct?.toFixed(2),'0.45');
assert.equal(matched[1]?.premiumPct,null,'never compare NAV and close from different trade dates');
assert.deepEqual(parseEtfNavRows({netPrice:[{date:'2026/10/08',count:'未結出'}]}),[]);
const candles:Array<DailyCandle>=Array.from({length:43},(_,i)=>({date:'2026-08-'+String(i+1).padStart(2,'0'),
  open:100+i,high:103+i,low:98+i,close:101+i,volume:100+i,source:'TWSE'}));
const source=JSON.stringify(candles),signals=computeTechnicalSignals(candles);
assert.equal(signals.length,43);
assert.equal(signals[0]?.k,null);
assert.ok(signals[9]?.k!==null&&signals[9]?.d!==null);
assert.equal(signals[20]?.dif,null,'MACD must not fake a full warmup');
assert.ok(signals[40]?.dif!==null&&signals[40]?.dea!==null);
assert.equal(JSON.stringify(candles),source);
const market=readFileSync('src/screens/MarketResearchScreen.tsx','utf8');
const technical=readFileSync('src/components/MarketTechnicalSignals.tsx','utf8');
const settings=readFileSync('src/screens/SettingsScreen.tsx','utf8');
assert.match(market,/fetchTwseInstitutionalSeries\(symbol,institutionalDays/);
assert.match(market,/matchOfficialNavToClose\(navRows,candles\)/);
assert.match(market,/MarketTechnicalSignals candles=\{transformed\}/);
assert.match(technical,/computeTechnicalSignals\(candles\)/);
assert.doesNotMatch(settings,/MarketTechnicalSignals|fetchOfficialEtfNavHistory/);
const app=JSON.parse(readFileSync('app.json','utf8')).expo;
assert.ok(Number(app.version.split('.')[2])>=29);assert.ok(app.android.versionCode>=40029);
console.log('V4.0.29 official T86 dynamic field contract, date-matched ETF NAV and warmup-safe KD/MACD: PASS');
