const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const file='src/settings/displayFormat.ts';
const moduleUnderTest={exports:{}};
if(fs.existsSync(file))new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(require,moduleUnderTest,moduleUnderTest.exports);
const {formatAmount,formatPercent,formatDate,scaledFontSize}=moduleUnderTest.exports;
assert.equal(typeof formatAmount,'function','saved amount preferences need a display consumer');
const prefs={fontScale:1.2,amountDecimals:2,percentDecimals:1,thousandsSeparator:false,dateFormat:'YYYY/MM/DD'};
assert.equal(formatAmount(1234.5,prefs),'1234.50');
assert.equal(formatAmount(-1234.5,{...prefs,thousandsSeparator:true}),'-1,234.50');
assert.equal(formatAmount(0,prefs),'0.00');
assert.equal(formatAmount(1234.5,{...prefs,amountDecimals:0}),'1235');
assert.equal(formatAmount(NaN,prefs),'待核對');
assert.equal(formatPercent(-1.234,prefs),'-1.2%');
assert.equal(formatPercent(2,{...prefs,percentDecimals:0}),'2%');
assert.equal(formatDate('2026-10-09',prefs),'2026/10/09');
assert.equal(formatDate('2026-02-30',prefs),'2026-02-30','do not invent a valid date');
assert.equal(formatDate('尚未公告',prefs),'尚未公告');
assert.equal(scaledFontSize(10,prefs),12);
assert.equal(scaledFontSize(10,{fontScale:NaN}),10);
console.log('V4.0.15 display preference behavior PASS');
