const assert=require('node:assert/strict');
const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');
const market=read('src/market/MarketRuntime.tsx');
const finance=read('src/finance/FinanceRuntime.tsx');
const app=read('App.tsx');
const bridge=read('src/native/TfAssetNativeBridge.ts');
const native=read('native/android/TfAssetNativeModule.kt');
const widget=read('native/android/TfAssetWidgetProvider.kt');
const overlay=read('native/android/TfAssetOverlayService.kt');
const pkg=JSON.parse(read('package.json'));
const appIdentity=JSON.parse(read('app.json'));
const stream=read('native/android/SaiEtfFugleStreamingController.kt');
const presentation=read('native/android/TfAssetMarketPresentation.kt');
assert.doesNotMatch(market,/marketRefreshSeconds|setInterval\(read,1000\)|setInterval\(tick,1000\)/,'JS market must not poll on fixed cadence');
assert.match(market,/subscribeUnifiedMarketData\(applySnapshot\)/,'Fugle hot-store event must be consumed');
assert.doesNotMatch(finance,/setInterval\(\(\)=>setValuationNow\(Date\.now\(\)\),30_000\)/,'finance must expire at source deadline');
assert.match(finance,/\[market\.marketDataVersion\]/,'a new SaiETF market version must advance the valuation clock');
assert.doesNotMatch(app,/setInterval\(\(\)=>\{void poll\(\);\},1000\)/,'surfaces must not poll request flags');
assert.match(bridge,/subscribeNativeMarketRefreshRequests/,'Native manual requests must be delivered as events');
assert.match(native,/SaiEtfMarketRefreshRequested/,'Native must emit manual request event to active App');
assert.doesNotMatch(widget,/已送出更新要求/,'Widget must not claim an update happened while App may be stopped');
assert.doesNotMatch(overlay,/coerceIn\(1L,30_000L\)/,'Mini/Monitor expiry must not spin on 30s cadence');
assert.match(stream,/onProviderDegraded\(event\.health\)/,'provider failure must trigger SaiETF fallback without JS polling');
assert.match(presentation,/now-at>30_000L/,'native surfaces must label a quiet last trade as delayed');
assert.match(presentation,/updatedAt[\s\S]*30_000L/,'native floating surfaces must redraw once at the source freshness deadline');
assert.ok(/^4\.0\.\d+$/.test(pkg.version)&&Number(pkg.version.split('.')[2])>=10);
assert.equal(appIdentity.expo.android.versionCode,40000+Number(pkg.version.split('.')[2]));
console.log('V4.0.10 global event updates contract PASS');
