import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {EDITOR_DIMENSION_MIN,EDITOR_DIMENSION_MAX,normalizeEditorDimension} from '../src/editor/dimensionPolicy';
import {normalizeTargetOverride} from '../src/maintenance/inspectionModel';
import {readableDividendSummaryMetric} from '../src/dividend/dividendSummaryVisual';
import {normalizeEditorConfig} from '../src/editor/editorModel';
import {normalizeQuickBarLayout,resolveQuickBarButton} from '../src/domain/portfolioQuickBarLayout';
import {normalizeDashboardLayout} from '../src/domain/dashboardLayout';
import {frameResizeDimensions} from '../src/maintenance/frameResizeGesture';
import {normalizeFrameEffects,DEFAULT_FRAME_EFFECTS} from '../src/maintenance/frameEffects';
const text=(path:string)=>readFileSync(path,'utf8');
assert.equal(EDITOR_DIMENSION_MIN,1);
assert.ok(EDITOR_DIMENSION_MAX>=10000);
assert.equal(normalizeEditorDimension(-12,10),1);
assert.equal(normalizeEditorDimension(NaN,10),10);
assert.equal(normalizeEditorDimension(0,10,true),0);
const raw={width:12,height:8,backgroundColor:'#ABCDEF'};
const sized=readableDividendSummaryMetric(raw);
assert.equal(sized.width,12);
assert.equal(sized.height,8);
assert.deepEqual(raw,{width:12,height:8,backgroundColor:'#ABCDEF'},'presentation must not mutate stored edits');
assert.equal(readableDividendSummaryMetric({width:1,height:1}).height,1);
assert.equal(readableDividendSummaryMetric({backgroundColor:'#ABCDEF'}).width,undefined,'auto remains auto');
assert.deepEqual({width:normalizeTargetOverride({width:1,height:1}).width,height:normalizeTargetOverride({width:1,height:1}).height},{width:1,height:1});
assert.equal(normalizeTargetOverride({width:99,height:9}).width,99);
const page=normalizeEditorConfig('dividend',{'dividend-summary':{
  ...normalizeEditorConfig('dividend',{})['dividend-summary']!,width:1,height:1,minHeight:0,
}});
assert.equal(page['dividend-summary']?.width,1);
assert.equal(page['dividend-summary']?.height,1);
assert.equal(page['dividend-summary']?.minHeight,0);
const buttons=normalizeQuickBarLayout({button:{width:1,height:1,minHeight:1},overrides:{chart:{width:2,height:2}}});
assert.equal(resolveQuickBarButton(buttons,'first').height,1);
assert.equal(resolveQuickBarButton(buttons,'first').width,1);
assert.equal(resolveQuickBarButton(buttons,'chart').height,2);
assert.equal(resolveQuickBarButton(buttons,'chart').width,2);
const dashboard=normalizeDashboardLayout({overview:{minHeight:1},profitAnalysis:{cardHeight:1},profitDetail:{rowHeight:1}});
assert.equal(dashboard.overview.minHeight,1);
assert.equal(dashboard.profitAnalysis.cardHeight,1);
assert.equal(dashboard.profitDetail.rowHeight,1);
assert.deepEqual(frameResizeDimensions({width:200,height:200},-199,-199),{width:1,height:1});
assert.equal(normalizeFrameEffects({maxWidth:1},DEFAULT_FRAME_EFFECTS).maxWidth,1);
const tools=text('src/components/PageLayoutToolWorkbench.tsx');
const preview=text('src/components/DividendPreviewSelector.tsx');
const runtime=text('src/components/MetricTile.tsx');
const quick=text('src/components/PortfolioQuickBar.tsx');
const dividend=text('src/screens/DividendScreen.tsx');
assert.match(tools,/min={EDITOR_DIMENSION_MIN} max={EDITOR_DIMENSION_MAX} step={1}/);
assert.match(tools,/keyboardType="numeric" selectTextOnFocus/);
assert.match(tools,/文字／數值物件尺寸/,'text and value elements must have independent width and height editors');
assert.match(preview,/explicit\?\.width!==undefined/,'real text/value preview must respect stored widths');
assert.doesNotMatch(tools,/minCardWidth=\{dividendSummaryCard/);
assert.doesNotMatch(tools,/minCardHeight=\{dividendSummaryCard/);
assert.match(preview,/fixedWidth\?\{width:metricStyle.width,minWidth:1/);
assert.match(preview,/fixedHeight\?\{height:metricStyle.height,minHeight:1/);
assert.match(runtime,/minWidth:1,minHeight:1/);
assert.match(quick,/minHeight:v.height===null\?v.minHeight:Math.min\(v.minHeight,v.height\)/);
assert.equal((dividend.match(/<MetricTile label=/g)||[]).length,3);
const settings=text('src/screens/SettingsScreen.tsx');
assert.doesNotMatch(settings,/dimensionPolicy|readableDividendSummaryMetric/,
  'the protected settings screen remains unchanged apart from release labels');
console.log('V4.0.23 explicit 1px user widths/heights preserved from settings to preview and live components: PASS');
