import assert from 'node:assert/strict';
import {isIsoCalendarDate,validateDividendDates,reduceDividendPlans,restoreDividendPlans,dividendPlanStatus,dividendAutofill,type DividendPlan} from '../src/dividend/dividendPlans';
import {calculateCanonicalLedgerSnapshot,freezeTradeEntry} from '../src/finance/canonicalLedger';
const plan:DividendPlan={id:'p1',symbol:'0050',name:'元大台灣50',status:'forecast',paymentDate:'2026-10-15',lastBuyDate:'2026-09-30',exDate:'2026-10-01',recordDate:'2026-10-02',perShareAmount:2,sharesHeld:100,note:'公告'};
assert.equal(isIsoCalendarDate('2026-02-31'),false);
assert.equal(isIsoCalendarDate('2024-02-29'),true);
assert.equal(isIsoCalendarDate('2026-02-29'),false);
assert.ok(validateDividendDates({...plan,exDate:'2026-10-16'}));
assert.ok(validateDividendDates({...plan,lastBuyDate:plan.exDate}));
assert.equal(dividendAutofill('9999',[{symbol:'0050',name:'元大台灣50',shares:100}]).name,'');
assert.equal(dividendAutofill('9999',[{symbol:'0050',name:'元大台灣50',shares:100}]).shares,'');
let state={entries:[],dividendPlans:[]} as Parameters<typeof reduceDividendPlans>[0];
const act=(action:Parameters<typeof reduceDividendPlans>[1],today='2026-10-08')=>{const result=reduceDividendPlans(state,action,today);state=result.state;return result.error;};
assert.equal(act({type:'save',plan}),undefined);
assert.equal(calculateCanonicalLedgerSnapshot({initialCash:0,entries:state.entries,quotes:[]}).cashBalance,0,'forecast cannot affect cash');
assert.ok(act({type:'post',id:'p1'}),'forecast must be confirmed explicitly');
assert.equal(act({type:'confirm',id:'p1'}),undefined);
assert.ok(act({type:'post',id:'p1'}),'future date cannot be posted');
assert.equal(state.entries.length,0);
assert.equal(act({type:'post',id:'p1'},'2026-10-15'),undefined);
assert.equal(state.entries.length,1);
assert.equal(calculateCanonicalLedgerSnapshot({initialCash:0,entries:state.entries,quotes:[]}).cashBalance,190);
assert.equal(dividendPlanStatus(state.dividendPlans[0]!,state.entries),'paid');
assert.equal(act({type:'post',id:'p1'},'2026-10-15'),undefined);
assert.equal(state.entries.length,1,'replay must not credit twice');
assert.ok(act({type:'save',plan:{...plan,perShareAmount:3}},'2026-10-15'),'paid events cannot rewrite ledger');
assert.ok(act({type:'delete',id:'p1'},'2026-10-15'),'paid event cannot be removed independently');
assert.deepEqual(restoreDividendPlans(JSON.parse(JSON.stringify(state.dividendPlans))),state.dividendPlans);
assert.throws(()=>restoreDividendPlans([{...plan,paymentDate:'2026-02-31'}]));
state={entries:[],dividendPlans:[]};
assert.equal(act({type:'save',plan:{...plan,paymentDate:'',perShareAmount:null,sharesHeld:null}}),undefined,'unknown payment/amount can remain a forecast');
assert.ok(act({type:'confirm',id:'p1'}),'unknown amount/payment cannot confirm');
assert.equal(act({type:'save',plan}),undefined);
assert.equal(act({type:'confirm',id:'p1'}),undefined);
assert.equal(act({type:'save',plan:{...plan,perShareAmount:3,status:'confirmed'}}),undefined);
assert.equal(state.dividendPlans[0]!.status,'forecast','edited confirmation must be reviewed again');
assert.ok(act({type:'save',plan:{...plan,id:'p2'}}),'duplicate distribution must be edited, not added');
console.log('Strict dates / clean autofill / persisted forecasts / explicit confirmation / idempotent canonical cash PASS');

const moduleApi=require('../src/dividend/dividendPlans');
assert.equal(typeof moduleApi.dividendEligibleShares,'function','announced entitlement date must use ledger history');
const trades=[freezeTradeEntry({id:'b1',kind:'buy',symbol:'0050',name:'ETF',date:'2026-09-01',shares:100,price:10,tradeMode:'ROUND_LOT'}),freezeTradeEntry({id:'b2',kind:'buy',symbol:'0050',name:'ETF',date:'2026-10-01',shares:50,price:10,tradeMode:'ROUND_LOT'}),freezeTradeEntry({id:'s1',kind:'sell',symbol:'0050',name:'ETF',date:'2026-10-03',shares:25,price:10,tradeMode:'ROUND_LOT'})];
assert.equal(moduleApi.dividendEligibleShares(trades,'0050','2026-09-30','2026-10-01','2026-10-08'),100);
assert.equal(moduleApi.dividendEligibleShares(trades,'0050','','2026-10-01','2026-10-08'),100,'ex-day purchases do not receive this dividend');
assert.equal(moduleApi.dividendEligibleShares(trades,'0050','2026-10-10','2026-10-12','2026-10-08'),null,'future entitlement must be reviewed later');

import {dividendEventToPlan} from '../src/ai/dividendAssistant';
const aiPlan=dividendEventToPlan({id:'0050-2026-10-01',symbol:'0050',name:'ETF',exDate:'2026-10-01',lastPurchaseDate:'2026-09-30',recordDate:'',paymentDate:'',perShareAmount:2,eligibleShares:100,estimatedDividend:200,distributionYield:1,status:'待配發',alreadyRecorded:false});
assert.equal(aiPlan.paymentDate,'','AI must not substitute ex-date for payment');
assert.equal(aiPlan.status,'forecast');
assert.equal(aiPlan.sharesHeld,null,'AI estimated eligibility must be reviewed');
const existingReceipt={id:'manual-other',kind:'dividend' as const,symbol:'0050',name:'ETF',date:plan.paymentDate,perShareAmount:2,sharesHeld:99};
const duplicateResult=reduceDividendPlans({entries:[existingReceipt],dividendPlans:[{...plan,status:'confirmed'}]},{type:'post',id:plan.id},plan.paymentDate);
assert.ok(duplicateResult.error,'same distribution with different entitlement must be reviewed, not credited twice');
assert.equal(duplicateResult.state.entries.length,1);
const reviewedAi={...aiPlan,paymentDate:'2026-10-15',sharesHeld:100,status:'confirmed' as const,note:'已核對'};
const aiReplay=reduceDividendPlans({entries:[],dividendPlans:[reviewedAi]},{type:'import',plan:aiPlan},'2026-10-15');
assert.ok(aiReplay.error,'reimport must not overwrite user reviewed announcement');
assert.deepEqual(aiReplay.state.dividendPlans,[reviewedAi]);
assert.equal(reduceDividendPlans({entries:[],dividendPlans:[]},{type:'import',plan:aiPlan},'2026-10-15').error,undefined,'new AI announcement should import as a forecast');

assert.ok(reduceDividendPlans({entries:[],dividendPlans:[{...reviewedAi,id:'manual-other'}]},{type:'import',plan:aiPlan},'2026-10-15').error,'same ex-date distribution must not duplicate when payment date differs');
