import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {marketPricePath} from '../src/domain/marketChartGeometry';
import {computeTechnicalSignals} from '../src/market/marketTechnicalSignals';
import {parseTpexInstitutional} from '../src/market/tpexInstitutional';
import type {DailyCandle} from '../src/market/twseDailyHistory';
const candles:DailyCandle[]=Array.from({length:45},(_,i)=>{
  const date=new Date(Date.UTC(2026,7,1+i)).toISOString().slice(0,10);
  return {date,open:90+i,high:94+i,low:88+i,close:91+i,volume:1+i,source:'TWSE'};
});
const old=JSON.stringify(candles);
const geometry=marketPricePath(candles,18,3,160);
assert.ok(geometry);
assert.equal(geometry!.points.length,45);
assert.equal(geometry!.points[0]?.x,12);
assert.equal(geometry!.points[1]?.x,30);
assert.ok(geometry!.points[1]!.y<geometry!.points[0]!.y);
assert.equal(geometry!.line.split(' ').length,45);
assert.equal(geometry!.area.split(' ').length,47);
assert.ok(!geometry!.line.includes('NaN'));
assert.equal(marketPricePath(candles.slice(0,1),18,3,160),null,'one candle cannot form a continuous line');
assert.equal(marketPricePath([{...candles[0]!,close:0},candles[1]!],18,3,160),null,'invalid quote is not drawn');
assert.equal(JSON.stringify(candles),old,'historical official input must remain immutable');
const signals=computeTechnicalSignals(candles);
const target=signals[22]!;
assert.ok(target.k!==null);
assert.ok(signals[44]!.k!==target.k);
const chart=readFileSync('src/components/OfficialCandleChart.tsx','utf8');
const screen=readFileSync('src/screens/MarketResearchScreen.tsx','utf8');
const indicator=readFileSync('src/components/MarketTechnicalSignals.tsx','utf8');
const parser=readFileSync('src/market/tpexInstitutional.ts','utf8');
assert.match(chart,/Polyline points=\{lineGeometry\.line\}/,'line mode must render actual price lines');
assert.match(chart,/Polygon points=\{lineGeometry\.area\}/,'area must be a real filled price shape');
assert.match(chart,/onSelectCandle\?\.\(candle\)/);
assert.match(chart,/selectedIndex=selected\?ordered\.findIndex/,'crosshair matches last displayed candle by default');
assert.match(screen,/crosshairDefault=\{false\}/,'default horizontal scrolling remains available');
assert.match(screen,/setSelectedCandleDate\(candle\.date\)/);
assert.match(screen,/selectedDate=\{selectedCandleDate\}/);
assert.match(indicator,/selectedDate\?signals\.find/,'indicator details follow selected trade date');
assert.match(parser,/replace\(/,'TPEx numeric and ticker HTML markup stripped');
assert.match(parser,/資料格式已變更/,'TPEx schema drift must surface an explicit error');
assert.doesNotMatch(readFileSync('src/screens/SettingsScreen.tsx','utf8'),/MarketTechnicalSignals|marketPricePath/);
assert.doesNotMatch(readFileSync('src/finance/FinanceRuntime.tsx','utf8'),/marketPricePath|tpexInstitutional/);
const identity=JSON.parse(readFileSync('app.json','utf8')).expo;
assert.equal(identity.version,'4.0.31');assert.equal(identity.android.versionCode,40031);
console.log('V4.0.31 real line/area chart geometry, scroll/crosshair selection, indicator synchronization, TPEx source safety: PASS');
