import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseTaiexMis,parseTaiexFmtqik,pickTaiexDisplay,selectTaiexHistory,taiex52WeekCloseRange} from '../src/market/taiexIndex';
const mis={msgArray:[{c:'t00',ch:'t00.tw',d:'20261008',t:'13:30:00',z:'49,313.44',y:'49,806.37',o:'49,783.06',h:'49,783.06',l:'49,189.77'}]};
const actual=parseTaiexMis(mis);
assert.ok(actual);assert.equal(actual!.value,49313.44);
assert.equal(actual!.previousClose,49806.37);assert.equal(actual!.open,49783.06);
assert.equal(parseTaiexMis({msgArray:[{...mis.msgArray[0],c:'2330',ch:'2330.tw'}]}),null,'reject equity quote');
assert.equal(parseTaiexMis({msgArray:[{...mis.msgArray[0],z:'-'}]}),null,'absent tick must not silently use previous close');
assert.equal(parseTaiexMis({msgArray:[{...mis.msgArray[0],d:'20260230'}]}),null,'reject impossible trade date');
const official={stat:'OK',fields:['日期','成交股數','成交金額','成交筆數','發行量加權股價指數','漲跌點數'],
  data:[['115/10/07','10,357,959,027','986,280,041,197','4,929,172','49,806.37','-16.18'],
        ['115/10/08','10,437,288,727','924,509,097,873','5,075,757','49,313.44','-492.93']]};
const rows=parseTaiexFmtqik(official);
assert.equal(rows.length,2);
assert.equal(rows[1]!.close,49313.44);assert.equal(rows[1]!.change,-492.93);
assert.deepEqual(parseTaiexFmtqik({stat:'OK',fields:['日期','收盤指數'],data:official.data}),[],'reject mismatched schema');
const lastClose=pickTaiexDisplay(actual,rows,'2026-10-11','afterHours');
assert.ok(lastClose);assert.equal(lastClose!.value,49313.44);
assert.equal(lastClose!.fromClose,true,'official close takes precedence over MIS after market close');
assert.equal(lastClose!.open,null,'historical closing record must not invent a session open');
assert.equal(lastClose!.change,-492.93);
const live=pickTaiexDisplay(actual,rows,'2026-10-08','live');
assert.equal(live?.live,true);
assert.equal(live?.open,49783.06);
assert.equal(live?.percent?.toFixed(2),'-0.99');
assert.equal(pickTaiexDisplay(null,rows,'2026-10-11','afterHours')?.source,'TWSE FMTQIK');
assert.equal(selectTaiexHistory(rows,'d5','2026-10-11').length,2);
assert.equal(taiex52WeekCloseRange(rows,'2026-10-11'),null,'do not pretend a few points cover 52 weeks');
const ui=readFileSync('src/components/TaiexIndexCard.tsx','utf8');
const screen=readFileSync('src/screens/MarketResearchScreen.tsx','utf8');
const registry=readFileSync('src/domain/frameRegistry.ts','utf8');
const runtime=readFileSync('src/market/MarketRuntime.tsx','utf8');
assert.match(screen,/key:'market-index'/);
assert.ok(screen.indexOf("key:'market-index'")<screen.indexOf("key:'market-search'"),'index header is above search');
assert.match(registry,/key:'market-index',title:'台股加權指數'/);
assert.match(ui,/marketVersion/);assert.match(ui,/phase/);
assert.match(ui,/range==='d1'\?points:/);
assert.match(ui,/官方最後收盤/);
assert.match(ui,/52週收盤高點/);
assert.match(ui,/TWSE MIS／FMTQIK/);
assert.doesNotMatch(runtime,/TaiexIndexCard|market-taiex-index/,'index read model cannot mutate SaiETF quote SSOT');
assert.doesNotMatch(readFileSync('src/finance/FinanceRuntime.tsx','utf8'),/taiexIndex/);
assert.doesNotMatch(readFileSync('src/screens/SettingsScreen.tsx','utf8'),/TaiexIndexCard|taiexIndex/);
const identity=JSON.parse(readFileSync('app.json','utf8')).expo;
assert.equal(identity.version,'4.0.32');assert.equal(identity.android.versionCode,40032);
console.log('V4.0.32 TWSE TAIEX live and official close, no fabricated values, editor frame and account isolation PASS');
