import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseTpexInstitutional} from '../src/market/tpexInstitutional';
const create=(symbol='00679B',foreign=400,trust=-300,dealer=100)=>{
  const triple=(a:number,b:number)=>[String(a),String(b),String(a-b)];
  const f=foreign>=0?triple(foreign,0):triple(0,-foreign);
  const t=trust>=0?triple(trust,0):triple(0,-trust);
  const o=dealer>=0?triple(dealer,0):triple(0,-dealer);
  const buyNet=(vals:string[])=>Number(vals[2]);
  const total=foreign+trust+dealer;
  return [symbol,'國泰20年美債',...f,...triple(0,0),...f,...t,...triple(0,0),...o,...o,String(total)];
};
const data=create();
assert.equal(data.length,24);
const doc={iTotalRecords:1,aaData:[data],reportDate:'115/10/07'};
const record=parseTpexInstitutional(doc,'00679B','2026-10-07',9876);
assert.deepEqual(record&&[record.foreign,record.trust,record.dealer,record.total,record.source,record.fetchedAt],[400,-300,100,200,'TPEx 三大法人日報',9876]);
assert.equal(parseTpexInstitutional(doc,'00679B','2026-10-08'),null,'reject wrong report date');
assert.equal(parseTpexInstitutional(doc,'00687B','2026-10-07'),null,'no cross-symbol values');
assert.equal(parseTpexInstitutional({...doc,aaData:[data.slice(0,20)]},'00679B','2026-10-07'),null,'reject missing trailing totals');
assert.equal(parseTpexInstitutional({...doc,iTotalRecords:0},'00679B','2026-10-07'),null,'report count not aligned');
const corrupt=[...data];corrupt[4]='999';
assert.equal(parseTpexInstitutional({...doc,aaData:[corrupt]},'00679B','2026-10-07'),null,'net must match buy minus sell');
const wrongTotal=[...data];wrongTotal[23]='999';
assert.equal(parseTpexInstitutional({...doc,aaData:[wrongTotal]},'00679B','2026-10-07'),null,'total must equal official sectors');
const invalid=[...data];invalid[4]='—';
assert.equal(parseTpexInstitutional({...doc,aaData:[invalid]},'00679B','2026-10-07'),null,'missing is not zero');
const screen=readFileSync('src/screens/MarketResearchScreen.tsx','utf8');
assert.match(screen,/fetchTpexInstitutionalSeries\(symbol,institutionalDays/);
assert.match(screen,/fetchTwseInstitutionalSeries\(symbol,institutionalDays/);
assert.match(screen,/info\.market==='TPEx'/);
assert.match(screen,/row\.source/);
assert.doesNotMatch(readFileSync('src/screens/SettingsScreen.tsx','utf8'),/TpexInstitutional/);
assert.doesNotMatch(readFileSync('src/finance/FinanceRuntime.tsx','utf8'),/TpexInstitutional/);
const version=JSON.parse(readFileSync('app.json','utf8')).expo;
assert.ok(Number(version.version.split('.')[2])>=30);assert.ok(version.android.versionCode>=40030);
console.log('V4.0.30 official TPEx parser, arithmetic, date / symbol safety, protected settings: PASS');
