import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p:string)=>fs.readFileSync(p,'utf8');
const runtime=read('src/market/MarketRuntime.tsx');
const finance=read('src/finance/FinanceRuntime.tsx');
const native=read('native/android/SaiEtfMarketRuntime.kt');
const bridge=read('native/android/TfAssetNativeModule.kt');
const settings=read('src/screens/SettingsScreen.tsx');
assert.doesNotMatch(runtime,/marketRefreshSeconds|setInterval\(tick,1000\)/,'SaiETF event policy has no legacy fixed cadence');
assert.doesNotMatch(runtime,/config\.stopAll|config\.scheduleEnabled|config\.live|config\.afterHours|refreshOnForeground/,'retired scheduler cannot override SaiETF');
assert.match(runtime,/subscribeUnifiedMarketData\(applySnapshot\)/,'memory ticks push directly to RN');
assert.match(finance,/setTrackedSymbols\(snapshot\.holdings\.map\(holding=>holding\.etfCode\)\)/,'only current positions subscribe');
assert.match(native,/quotesState\.collectLatest[\s\S]*version\.incrementAndGet/,'Fugle tick advances visible data version');
assert.match(bridge,/RCTDeviceEventEmitter[\s\S]*SaiEtfMarketSnapshot/,'native hot store emits snapshot');
assert.match(runtime,/updateNativeMarketSymbols\(combinedSymbols\(\)\)/,'changes to holdings or research symbols update the unified Fugle subscriptions');
assert.match(runtime,/setResearchSymbolsState\(current=>sameStrings\(current,next\)\?current:next\)/,'research subscription state is independent of holdings');
assert.doesNotMatch(native.slice(native.indexOf('@Synchronized fun refresh'),native.indexOf('fun snapshot(')),/updateSymbols\(symbols\)/,
  'ad-hoc AI quote refresh must not replace holdings WebSocket subscriptions');
assert.match(runtime,/next==='active'[\s\S]*updateNativeMarketSymbols\(combinedSymbols\(\)\)/,'resume restores both held and selected research symbols');
assert.match(runtime,/next==='background'[\s\S]*pauseNativeMarketStreaming\(\)/,'background pauses streaming like SaiETF');
assert.doesNotMatch(settings,/label="停止全部自動更新"|label="盤中更新頻率"|label="盤後更新頻率"/);
console.log('SaiETF update policy / current holdings / event bridge ownership PASS');
