const fs=require('fs');
const must=(p,s)=>{const c=fs.readFileSync(p,'utf8');if(!c.includes(s))throw new Error(p+' missing '+s);};
must('src/widget/widgetDomain.ts','WidgetStyle');
must('src/widget/widgetDomain.ts','WidgetEffects');
must('src/widget/widgetDomain.ts','WidgetSort');
must('src/widget/WidgetSettingsRuntime.tsx','fontScale:clamp');
must('src/components/widget/WidgetControlPanel.tsx','即時預覽');
must('src/components/widget/WidgetControlPanel.tsx','背景透明度');
must('src/monitor/monitorDomain.ts','normalStyle');
must('src/monitor/monitorDomain.ts','miniStyle');
must('src/monitor/monitorDomain.ts','updateActiveMonitorStyle');
must('src/components/monitor/MonitorControlPanel.tsx','Normal / Mini');
must('src/components/monitor/MonitorControlPanel.tsx','背景透明度');
must('src/native/TfAssetNativeBridge.ts','syncNativeWidget');
must('native/android/TfAssetWidgetProvider.kt','AppWidgetProvider');
must('native/android/TfAssetOverlayService.kt','TYPE_APPLICATION_OVERLAY');
must('native/android/TfAssetOverlayService.kt','toggleMode()');
must('App.tsx','syncNativeWidget(widgetSettings.config,finance.sharedSnapshot)');
must('App.tsx','syncNativeMonitor(monitorSettings.config,finance.sharedSnapshot)');
const settings=fs.readFileSync('src/screens/SettingsScreen.tsx','utf8');
if(!settings.includes("const VERSION="))throw new Error('SettingsScreen.tsx missing VERSION display');
console.log('V1.0.7 Widget/Monitor contract PASS');
