/** TF Asset backup document v2: actual settings + ledger + separate historic snapshots.
 * Never accept an empty payload as a "successful complete backup".
 */
export const TF_BACKUPS_KEY='@tf-asset/local-backups';
export const TF_LEDGER_KEY='@tf-asset/v1.0.2-ledger';
export const TF_LAST_EXTERNAL_BACKUP_KEY='@tf-asset/last-external-backup';
export type BackupHistoryEntry=Readonly<{
  id:string;createdAt:string;appVersion:string;keys:number;bytes:number;payload:Record<string,string>;
}>;
export type InspectedBackup=Readonly<{
  appVersion:string;exportedAt:string;keys:number;ledgerEntries:number;historyCount:number;bytes:number;
}>;

export function validBackupPayload(value:unknown):value is Record<string,string>{
  if(!value||typeof value!=='object'||Array.isArray(value))return false;
  return Object.entries(value as Record<string,unknown>).every(([key,item])=>
    key.startsWith('@tf-asset/')&&key!==TF_BACKUPS_KEY&&typeof item==='string'
  );
}
export function parseBackupDocument(text:string):{
  payload:Record<string,string>;history:BackupHistoryEntry[];inspection:InspectedBackup;
}{
  if(!text.trim()||text.length>32*1024*1024)throw new Error('備份文件為空或超出 32MB 限制');
  let parsed:Record<string,unknown>;
  try{parsed=JSON.parse(text) as Record<string,unknown>;}catch{throw new Error('備份不是有效的 JSON 文件');}
  if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)
    ||parsed.product!=='TF Asset'||(parsed.version!==1&&parsed.version!==2)
    ||typeof parsed.appVersion!=='string'||typeof parsed.exportedAt!=='string'
    ||!validBackupPayload(parsed.payload))throw new Error('不是有效的 TF Asset 備份格式');
  const payload=parsed.payload;
  const rawLedger=payload[TF_LEDGER_KEY];
  if(typeof rawLedger!=='string')throw new Error('備份檔缺少帳務 Ledger，不能視為完整備份');
  let ledger:Record<string,unknown>;
  try{ledger=JSON.parse(rawLedger) as Record<string,unknown>;}catch{throw new Error('備份檔帳務資料無法解析');}
  if(!ledger||typeof ledger!=='object'||ledger.schema!==1||!Array.isArray(ledger.entries)
    ||typeof ledger.initialCash!=='number'||!Number.isFinite(ledger.initialCash)){
    throw new Error('帳務 Ledger 結構不完整，已拒絕匯入');
  }
  const ids=new Set<string>();
  for(const entry of ledger.entries){
    if(!entry||typeof entry!=='object'||typeof entry.id!=='string'||!entry.id
      ||typeof entry.date!=='string'||!['buy','sell','dividend','other'].includes(entry.kind)
      ||ids.has(entry.id))throw new Error('帳務交易紀錄格式錯誤或存在重複 ID');
    ids.add(entry.id);
  }
  const rawHistory=parsed.version===2?parsed.backupHistory:[];
  if(!Array.isArray(rawHistory))throw new Error('歷史備份清單格式錯誤');
  const history:BackupHistoryEntry[]=[];
  for(const item of rawHistory){
    if(!item||typeof item!=='object'||typeof item.id!=='string'
      ||typeof item.createdAt!=='string'||typeof item.appVersion!=='string'
      ||typeof item.keys!=='number'||typeof item.bytes!=='number'
      ||!validBackupPayload(item.payload))throw new Error('歷史備份內容格式錯誤');
    history.push(item as BackupHistoryEntry);
  }
  return {payload,history,inspection:{
    appVersion:parsed.appVersion,exportedAt:parsed.exportedAt,
    keys:Object.keys(payload).length,ledgerEntries:ledger.entries.length,
    historyCount:history.length,bytes:text.length,
  }};
}
export function buildBackupDocument(input:{
  payload:Record<string,string>;history:readonly BackupHistoryEntry[];
  appVersion:string;exportedAt:string;
}):string{
  const document=JSON.stringify({
    product:'TF Asset',version:2,appVersion:input.appVersion,
    exportedAt:input.exportedAt,payload:input.payload,backupHistory:input.history,
  },null,2);
  // The generated bytes must be independently parsable before opening the Android file picker.
  parseBackupDocument(document);
  return document;
}
