export type FormulaRow=Readonly<{title:string;formula:string;note?:string}>;
export const FINANCE_FORMULA_CATALOG:readonly FormulaRow[]=[
{title:'成交金額',formula:'Math.floor(股數 × 成交價格)',note:'金額以元為單位，成交金額無條件捨去。'},
{title:'買進公式手續費',formula:'依券商費率 × 折扣 × 成交金額，再套用交易模式最低手續費與取整規則'},
{title:'買進實際手續費',formula:'有輸入 actualFee → 使用 actualFee；未輸入 → 使用公式手續費',note:'正式入帳後固化，不因日後券商設定改變而重算。'},
{title:'買進現金支出',formula:'成交金額 ＋ 實際手續費'},
{title:'賣出公式手續費',formula:'依券商費率 × 折扣 × 成交金額，再套用交易模式最低手續費與取整規則'},
{title:'ETF 賣出公式證交稅',formula:'依券商設定之 ETF 證交稅規則 × 成交金額並取整'},
{title:'賣出實際手續費',formula:'有輸入 actualFee → 使用 actualFee；未輸入 → 使用公式手續費'},
{title:'賣出實際證交稅',formula:'有輸入 actualTax → 使用 actualTax；未輸入 → 使用公式證交稅'},
{title:'賣出現金流入',formula:'成交金額 － 實際手續費 － 實際證交稅'},
{title:'歷史費稅固化',formula:'交易入帳後保存 actualFee / actualTax；Portfolio 與後續彙總不得依新費率重算'},
{title:'持有股數',formula:'歷史買進股數總和 － 歷史有效賣出股數總和'},
{title:'賣出成本釋放',formula:'賣出前平均成本 × 本次賣出股數',note:'採移動平均方式釋放純成交成本與含費成本。'},
{title:'剩餘純成交成本',formula:'買進純成交成本累積 － 賣出時釋放的純成交成本'},
{title:'純成交均價',formula:'剩餘純成交成本 ÷ 目前持有股數',note:'不包含任何買進手續費。'},
{title:'剩餘含費成本',formula:'買進成交金額＋實際買進手續費之累積 － 賣出時釋放的含費成本'},
{title:'含費成本均價',formula:'剩餘含費成本 ÷ 目前持有股數'},
{title:'目前市值',formula:'Math.floor(目前持有股數 × 即時市價)'},
{title:'預估賣出手續費',formula:'以目前市值與目前清算交易模式套用券商手續費規則'},
{title:'預估賣出證交稅',formula:'以目前市值套用 ETF 賣出證交稅規則'},
{title:'淨清算價值',formula:'目前市值 － 預估賣出手續費 － 預估賣出證交稅'},
{title:'純價差未實現損益',formula:'目前市值 － 剩餘純成交成本'},
{title:'淨清算未實現損益',formula:'淨清算價值 － 剩餘含費成本'},
{title:'未實現報酬率',formula:'淨清算未實現損益 ÷ 剩餘含費成本 × 100%'},
{title:'單筆已實現損益',formula:'該筆賣出淨收入 － 該筆釋放含費成本'},
{title:'累積已實現損益',formula:'所有有效賣出交易已實現損益加總'},
{title:'股息總額',formula:'Math.floor(符合配息股數 × 每股股息)'},
{title:'補充保費',formula:'股息總額達核心門檻時，Math.floor(股息總額 × 核心補充保費率)；否則 0'},
{title:'股息匯費',formula:'有股息時依核心股息匯費規則計入'},
{title:'股息淨收入',formula:'股息總額 － 補充保費 － 股息匯費'},
{title:'累積淨股息',formula:'歷史每筆股息淨收入加總'},
{title:'含息總損益',formula:'淨清算未實現損益 ＋ 累積已實現損益 ＋ 累積淨股息'},
{title:'現金餘額',formula:'期初現金 ＋ 所有帳務現金流',note:'買進為負、賣出/股息/其他收入依實際帳務現金流計入。'},
{title:'投資組合總市值',formula:'所有持股目前市值加總'},
{title:'總資產',formula:'投資組合總市值 ＋ 現金餘額'},
{title:'資產權重',formula:'個別 ETF 目前市值 ÷ 投資組合總市值 × 100%'},
{title:'下一次預估淨股息',formula:'目前持有股數 × 最新每股股息，再套用股息淨額規則'},
{title:'單期殖利率',formula:'最新每股股息 ÷ 目前市價 × 100%'},
{title:'年化殖利率',formula:'最新每股股息 × 年配息次數 ÷ 目前市價 × 100%'},
{title:'損益百分比顯示',formula:'百分比結果四捨五入至小數點後 2 位'},
{title:'無效輸入保護',formula:'非有限數值或負值依核心既定防護轉為安全值；零股數/零價格不產生交易金額'},
{title:'超賣保護',formula:'依交易日期順序逐筆驗證；任一賣出股數不得高於當時可用持股'},
];
